// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}

package {{ .GoPackage }}

{{- /* Three blocks: standard library, third-party, then the runtime. The
       third-party block is assembled and sorted in Go (see buildParams), since
       gofmt sorts within a block but never across them. */}}
import (
	"context"
{{- if .HasStreamProgress }}
	"errors"
	"fmt"
{{- end }}
{{- if .ExtraImports }}

{{- range .ExtraImports }}
	{{ . }}
{{- end }}
{{- end }}

	"github.com/the-protobuf-project/runtime-go/agents/mcp"
)


// JSON schemas for each RPC method, used as the inputSchema for MCP tools.
{{- range $key, $val := .SchemaJSON }}
var {{ $key }}SchemaJSON = {{ safeRawString $val }}
{{- end }}

// MCP tool descriptors. Each pairs a schema with a tool name and description
// so that LLM clients can discover and invoke the underlying RPCs.
var (
{{- range $key, $val := .SchemaJSON }}
	{{ $key }}Tool = mcp.MustCreateTool("{{ (index $.ToolMeta $key).Name }}", {{ safeRawString (index $.ToolMeta $key).Description }}, {{ $key }}SchemaJSON)
{{- end }}
)

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPServer is the interface that users implement to handle MCP
// tool calls backed by {{ $svcName }} RPCs. Unary RPCs take (ctx, req) and
// return (resp, error). Server-streaming RPCs (with MCPProgress) take (req,
// stream) matching the gRPC server interface — any type implementing
// {{ $svcName }}Server automatically satisfies this interface.
type {{ $svcName }}MCPServer interface {
{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{{ $methName }}(req *{{ $tool.RequestType }}, stream {{ $tool.StreamProgress.StreamServerType }}) error
{{- else }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}) (*{{ $tool.ResponseType }}, error)
{{- end }}
{{- end }}
}

// {{ $svcName }}MCPClient is the gRPC client interface used when forwarding MCP
// tool calls to a remote gRPC server. It matches the generated gRPC client stub.
type {{ $svcName }}MCPClient interface {
{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) ({{ $tool.StreamProgress.StreamClientType }}, error)
{{- else }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) (*{{ $tool.ResponseType }}, error)
{{- end }}
{{- end }}
}
{{- end }}

{{- /* ================================================================== */}}
{{- /* RegisterHandler                                                     */}}
{{- /* ================================================================== */}}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// Register{{ $svcName }}MCPHandler registers all {{ $svcName }} RPC methods as MCP
// tools, prompts, resources, and apps on the given server based on proto options.
func Register{{ $svcName }}MCPHandler(s *mcp.Server, srv {{ $svcName }}MCPServer, opts ...mcp.Option) {
	cfg := mcp.ApplyOptions(opts...)
	_ = cfg
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := mcp.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{
		tool := mcp.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcp.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcp.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ escapeQuotes .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
{{- if $tool.MethodOpts.Elicitation.IsURLMode }}
			var elicitResult *mcp.ElicitResult
			if elicitResp, answered := req.Params.InputResponses[mcp.ElicitRequestID]; answered {
				elicitResult, _ = elicitResp.(*mcp.ElicitResult)
			} else {
				return &mcp.CallToolResult{
					InputRequests: mcp.InputRequestMap{
						mcp.ElicitRequestID: &mcp.ElicitParams{
							Mode:    "url",
							Message: "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}",
							URL:     "{{ $tool.MethodOpts.Elicitation.URL }}",
{{- if $tool.MethodOpts.Elicitation.ElicitationID }}
							ElicitationID: "{{ $tool.MethodOpts.Elicitation.ElicitationID }}",
{{- end }}
						},
					},
				}, nil
			}
			if elicitResult == nil || elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- else }}
			elicitResult, elicitPending, elicitErr := mcp.RunElicitation(req, "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- end }}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcp.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			if elicitResult != nil {
				args = mcp.MergeElicitResult(args, elicitResult.Content, elicitFields)
			}
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			token := req.Params.GetProgressToken()
			session := req.Session
			// notifCtx is unbound so progress notifications are not tied to the
			// tool-call request lifetime.
			// grpcCtx detaches from the tool-call cancellation so the gRPC
			// server method can complete its stream after the HTTP response is sent.
			notifCtx := context.Background()
			grpcCtx := mcp.WithIncomingProgressToken(context.WithoutCancel(ctx), token)
			stream := mcp.NewInProcessServerStream[*{{ $tool.StreamProgress.StreamChunkType }}](grpcCtx)
			errCh := make(chan error, 1)
			go func() {
				defer stream.Close()
				// Streaming tools call the service directly: cfg.UnaryInterceptor
				// is unary-only (a grpc.StreamServerInterceptor has a different
				// shape), so unary middleware does not cover progress tools.
				errCh <- srv.{{ $methName }}(&pbReq, stream)
			}()
			go func() {
				for {
					chunk, ok := stream.Recv()
					if !ok {
						if err := <-errCh; err != nil {
							_ = mcp.SendDoneProgress(notifCtx, session, token, fmt.Sprintf(`{"error":%q}`, err.Error()))
						}
						return
					}
					switch {
					case chunk.Get{{ $tool.StreamProgress.ProgressField }}() != nil:
						// A chunk carrying its own progress token overrides the
						// request's; the runtime resolves that.
						_ = mcp.SendProgressFromProto(notifCtx, session, token, chunk.Get{{ $tool.StreamProgress.ProgressField }}())
					case chunk.Get{{ $tool.StreamProgress.ResultField }}() != nil:
						out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(chunk.Get{{ $tool.StreamProgress.ResultField }}())
						if err != nil {
							_ = mcp.SendDoneProgress(notifCtx, session, token, fmt.Sprintf(`{"error":%q}`, err.Error()))
						} else {
							_ = mcp.SendDoneProgress(notifCtx, session, token, string(out))
						}
						return
					}
				}
			}()
			return mcp.TextResult(`{"status":"started"}`), nil
		})
	}
{{- else }}
	{
		tool := mcp.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcp.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcp.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ escapeQuotes .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
{{- if $tool.MethodOpts.Elicitation.IsURLMode }}
			var elicitResult *mcp.ElicitResult
			if elicitResp, answered := req.Params.InputResponses[mcp.ElicitRequestID]; answered {
				elicitResult, _ = elicitResp.(*mcp.ElicitResult)
			} else {
				return &mcp.CallToolResult{
					InputRequests: mcp.InputRequestMap{
						mcp.ElicitRequestID: &mcp.ElicitParams{
							Mode:    "url",
							Message: "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}",
							URL:     "{{ $tool.MethodOpts.Elicitation.URL }}",
{{- if $tool.MethodOpts.Elicitation.ElicitationID }}
							ElicitationID: "{{ $tool.MethodOpts.Elicitation.ElicitationID }}",
{{- end }}
						},
					},
				}, nil
			}
			if elicitResult == nil || elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- else }}
			elicitResult, elicitPending, elicitErr := mcp.RunElicitation(req, "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- end }}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcp.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			if elicitResult != nil {
				args = mcp.MergeElicitResult(args, elicitResult.Content, elicitFields)
			}
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			// Dispatch through the unary interceptor chain (when configured) so
			// middleware sees this call exactly as it would the wire RPC.
			rawResp, err := mcp.InvokeUnary(ctx, cfg.UnaryInterceptor, "{{ $tool.FullMethod }}", srv, &pbReq, func(ctx context.Context, req any) (any, error) {
				return srv.{{ $methName }}(ctx, req.(*{{ $tool.RequestType }}))
			})
			if err != nil {
				return mcp.HandleError(err)
			}
			resp := rawResp.(*{{ $tool.ResponseType }})
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return mcp.TextResult(string(out)), nil
		})
	}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ escapeQuotes .URI }}",
		Name:        "{{ escapeQuotes .Name }}",
{{- if .Title }}
		Title:       "{{ escapeQuotes .Title }}",
{{- end }}
		Description: "{{ escapeQuotes .Description }}",
		MIMEType:    "{{ escapeQuotes .MimeType }}",
{{- if .HasSize }}
		Size:        {{ .Size }},
{{- end }}
{{- with .Annotations }}
		Annotations: &mcp.Annotations{
{{- if .Audience }}
			Audience:     []mcp.Role{ {{- range .Audience }}"{{ . }}", {{ end }}},
{{- end }}
{{- if .LastModified }}
			LastModified: "{{ escapeQuotes .LastModified }}",
{{- end }}
{{- if .HasPriority }}
			Priority:     {{ .Priority }},
{{- end }}
		},
{{- end }}
{{- if .Icons }}
		Icons: []mcp.Icon{
{{- range .Icons }}
			{Source: "{{ escapeQuotes .Src }}"{{ if .MimeType }}, MIMEType: "{{ escapeQuotes .MimeType }}"{{ end }}{{ if .Sizes }}, Sizes: []string{ {{- range .Sizes }}"{{ escapeQuotes . }}", {{ end }}}{{ end }}{{ if .Theme }}, Theme: "{{ escapeQuotes .Theme }}"{{ end }}},
{{- end }}
		},
{{- end }}
	}, mcp.ResourceHandlerFor(cfg, "{{ escapeQuotes .URI }}", mcp.DefaultResourceHandler()))
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ escapeQuotes .URITemplate }}",
		Name:        "{{ escapeQuotes .Name }}",
{{- if .Title }}
		Title:       "{{ escapeQuotes .Title }}",
{{- end }}
		Description: "{{ escapeQuotes .Description }}",
		MIMEType:    "{{ escapeQuotes .MimeType }}",
{{- with .Annotations }}
		Annotations: &mcp.Annotations{
{{- if .Audience }}
			Audience:     []mcp.Role{ {{- range .Audience }}"{{ . }}", {{ end }}},
{{- end }}
{{- if .LastModified }}
			LastModified: "{{ escapeQuotes .LastModified }}",
{{- end }}
{{- if .HasPriority }}
			Priority:     {{ .Priority }},
{{- end }}
		},
{{- end }}
{{- if .Icons }}
		Icons: []mcp.Icon{
{{- range .Icons }}
			{Source: "{{ escapeQuotes .Src }}"{{ if .MimeType }}, MIMEType: "{{ escapeQuotes .MimeType }}"{{ end }}{{ if .Sizes }}, Sizes: []string{ {{- range .Sizes }}"{{ escapeQuotes . }}", {{ end }}}{{ end }}{{ if .Theme }}, Theme: "{{ escapeQuotes .Theme }}"{{ end }}},
{{- end }}
		},
{{- end }}
	}, mcp.ResourceHandlerFor(cfg, "{{ escapeQuotes .URITemplate }}", mcp.DefaultResourceHandler()))
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ escapeQuotes .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, func(_ context.Context, _ *mcp.GetPromptRequest) (*mcp.GetPromptResult, error) {
		// Placeholder handler carrying the role declared in the proto. Replace it
		// via server.RemovePrompts / server.AddPrompt with your own handler.
		return &mcp.GetPromptResult{
			Description: "{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}",
			Messages: []*mcp.PromptMessage{
				{
					Role:    "{{ $tool.MethodOpts.Prompt.Role }}",
					Content: &mcp.TextContent{Text: "{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"},
				},
			},
		}, nil
	})
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, mcp.ResourceHandlerFor(cfg, appResourceURI, mcp.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}")))
{{- end }}
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPDefaultBasePath is the default HTTP path prefix for
// {{ $svcName }} MCP endpoints, derived from the protobuf package and service name.
const {{ $svcName }}MCPDefaultBasePath = "{{ index $.ServiceBasePaths $svcName }}"
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// {{ $svcName }}CompletionMap returns a map of "promptName:argName" → allowed
// values, built from enum_values declared in the proto MCP options.
func {{ $svcName }}CompletionMap() map[string][]string {
	m := map[string][]string{}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
{{- $pName := $tool.MethodOpts.Prompt.Name }}
{{- range $tool.MethodOpts.Prompt.Arguments }}
{{- if .EnumValues }}
	m["{{ $pName }}:{{ .Name }}"] = []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
	return m
}

// Serve{{ $svcName }}MCP creates an MCP server, registers the service tools, and
// starts serving using the configured transport (streamable-http, sse, or stdio).
// Uses the proto-derived BasePath. This is a blocking call.
func Serve{{ $svcName }}MCP(ctx context.Context, srv {{ $svcName }}MCPServer, cfg *mcp.MCPServerConfig, opts ...mcp.Option) error {
	// Set the proto-derived path as the generated default
	cfg.GeneratedBasePath = {{ $svcName }}MCPDefaultBasePath

	// Wire completion handler for prompt arguments with enum_values.
	completionMap := {{ $svcName }}CompletionMap()
	if len(completionMap) > 0 {
		if cfg.ServerOptions == nil {
			cfg.ServerOptions = &mcp.ServerOptions{}
		}
		cfg.ServerOptions.CompletionHandler = mcp.CompletionHandlerFromEnums(completionMap)
	}

	// Forward the hosting server's unary interceptor chain so every tool call
	// runs the same middleware (validation, auth, tracing) as the wire RPC.
	if cfg.UnaryInterceptor != nil {
		opts = append(opts, mcp.WithUnaryInterceptor(cfg.UnaryInterceptor))
	}

	return mcp.StartServer(ctx, cfg, func(s *mcp.Server) {
		Register{{ $svcName }}MCPHandler(s, srv, opts...)
	})
}
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// ForwardTo{{ $svcName }}MCPClient registers all {{ $svcName }} tools, prompts,
// resources, and apps on the MCP server, forwarding every tool call to a
// remote gRPC server via the provided client stub.
func ForwardTo{{ $svcName }}MCPClient(s *mcp.Server, client {{ $svcName }}MCPClient, opts ...mcp.Option) {
	cfg := mcp.ApplyOptions(opts...)
	_ = cfg
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := mcp.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
	{
		tool := mcp.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcp.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcp.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ escapeQuotes .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
{{- if $tool.MethodOpts.Elicitation.IsURLMode }}
			var elicitResult *mcp.ElicitResult
			if elicitResp, answered := req.Params.InputResponses[mcp.ElicitRequestID]; answered {
				elicitResult, _ = elicitResp.(*mcp.ElicitResult)
			} else {
				return &mcp.CallToolResult{
					InputRequests: mcp.InputRequestMap{
						mcp.ElicitRequestID: &mcp.ElicitParams{
							Mode:    "url",
							Message: "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}",
							URL:     "{{ $tool.MethodOpts.Elicitation.URL }}",
{{- if $tool.MethodOpts.Elicitation.ElicitationID }}
							ElicitationID: "{{ $tool.MethodOpts.Elicitation.ElicitationID }}",
{{- end }}
						},
					},
				}, nil
			}
			if elicitResult == nil || elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- else }}
			elicitResult, elicitPending, elicitErr := mcp.RunElicitation(req, "{{ escapeQuotes $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
{{- if $tool.MethodOpts.Elicitation.Required }}
				return mcp.TextResult("Action cancelled by user."), nil
{{- else }}
				// required is false: proceed with the LLM-provided arguments.
				elicitResult = nil
{{- end }}
			}
{{- end }}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcp.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			if elicitResult != nil {
				args = mcp.MergeElicitResult(args, elicitResult.Content, elicitFields)
			}
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			ctx = mcp.ForwardMetadata(ctx)
{{- if $tool.StreamProgress }}
			if token := req.Params.GetProgressToken(); token != nil {
				ctx = mcp.WithProgressToken(ctx, token)
			}
			stream, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return mcp.HandleError(err)
			}
			token := req.Params.GetProgressToken()
			for {
				chunk, err := stream.Recv()
				if err != nil {
					if errors.Is(err, context.Canceled) {
						return nil, err
					}
					return mcp.HandleError(err)
				}
				switch {
				case chunk.Get{{ $tool.StreamProgress.ProgressField }}() != nil:
					// A chunk carrying its own progress token overrides the
					// request's; the runtime resolves that.
					_ = mcp.SendProgressFromProto(ctx, req.Session, token, chunk.Get{{ $tool.StreamProgress.ProgressField }}())
				case chunk.Get{{ $tool.StreamProgress.ResultField }}() != nil:
					out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(chunk.Get{{ $tool.StreamProgress.ResultField }}())
					if err != nil {
						return nil, err
					}
					return mcp.TextResult(string(out)), nil
				}
			}
{{- else }}
			resp, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return mcp.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return mcp.TextResult(string(out)), nil
{{- end }}
		})
	}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ escapeQuotes .URI }}",
		Name:        "{{ escapeQuotes .Name }}",
{{- if .Title }}
		Title:       "{{ escapeQuotes .Title }}",
{{- end }}
		Description: "{{ escapeQuotes .Description }}",
		MIMEType:    "{{ escapeQuotes .MimeType }}",
{{- if .HasSize }}
		Size:        {{ .Size }},
{{- end }}
{{- with .Annotations }}
		Annotations: &mcp.Annotations{
{{- if .Audience }}
			Audience:     []mcp.Role{ {{- range .Audience }}"{{ . }}", {{ end }}},
{{- end }}
{{- if .LastModified }}
			LastModified: "{{ escapeQuotes .LastModified }}",
{{- end }}
{{- if .HasPriority }}
			Priority:     {{ .Priority }},
{{- end }}
		},
{{- end }}
{{- if .Icons }}
		Icons: []mcp.Icon{
{{- range .Icons }}
			{Source: "{{ escapeQuotes .Src }}"{{ if .MimeType }}, MIMEType: "{{ escapeQuotes .MimeType }}"{{ end }}{{ if .Sizes }}, Sizes: []string{ {{- range .Sizes }}"{{ escapeQuotes . }}", {{ end }}}{{ end }}{{ if .Theme }}, Theme: "{{ escapeQuotes .Theme }}"{{ end }}},
{{- end }}
		},
{{- end }}
	}, mcp.ResourceHandlerFor(cfg, "{{ escapeQuotes .URI }}", mcp.DefaultResourceHandler()))
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ escapeQuotes .URITemplate }}",
		Name:        "{{ escapeQuotes .Name }}",
{{- if .Title }}
		Title:       "{{ escapeQuotes .Title }}",
{{- end }}
		Description: "{{ escapeQuotes .Description }}",
		MIMEType:    "{{ escapeQuotes .MimeType }}",
{{- with .Annotations }}
		Annotations: &mcp.Annotations{
{{- if .Audience }}
			Audience:     []mcp.Role{ {{- range .Audience }}"{{ . }}", {{ end }}},
{{- end }}
{{- if .LastModified }}
			LastModified: "{{ escapeQuotes .LastModified }}",
{{- end }}
{{- if .HasPriority }}
			Priority:     {{ .Priority }},
{{- end }}
		},
{{- end }}
{{- if .Icons }}
		Icons: []mcp.Icon{
{{- range .Icons }}
			{Source: "{{ escapeQuotes .Src }}"{{ if .MimeType }}, MIMEType: "{{ escapeQuotes .MimeType }}"{{ end }}{{ if .Sizes }}, Sizes: []string{ {{- range .Sizes }}"{{ escapeQuotes . }}", {{ end }}}{{ end }}{{ if .Theme }}, Theme: "{{ escapeQuotes .Theme }}"{{ end }}},
{{- end }}
		},
{{- end }}
	}, mcp.ResourceHandlerFor(cfg, "{{ escapeQuotes .URITemplate }}", mcp.DefaultResourceHandler()))
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ escapeQuotes .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, func(_ context.Context, _ *mcp.GetPromptRequest) (*mcp.GetPromptResult, error) {
		// Placeholder handler carrying the role declared in the proto. Replace it
		// via server.RemovePrompts / server.AddPrompt with your own handler.
		return &mcp.GetPromptResult{
			Description: "{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}",
			Messages: []*mcp.PromptMessage{
				{
					Role:    "{{ $tool.MethodOpts.Prompt.Role }}",
					Content: &mcp.TextContent{Text: "{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"},
				},
			},
		}, nil
	})
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, mcp.ResourceHandlerFor(cfg, appResourceURI, mcp.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}")))
{{- end }}
}
{{- end }}
