// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}

package {{ .GoPackage }}

import (
	"context"
{{- if .HasStreamProgress }}
	"errors"
	"fmt"
{{- end }}

{{- range .ExtraImports }}
	{{ . }}
{{- end }}
	"github.com/modelcontextprotocol/go-sdk/mcp"
{{- if .HasAnyMethods }}
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"
{{- end }}

	"github.com/the-protobuf-project/runtime-go/mcpruntime"
)

// JSON schemas for each RPC method, used as the inputSchema for MCP tools.
{{- range $key, $val := .SchemaJSON }}
var {{ $key }}SchemaJSON = {{ safeRawString $val }}
{{- end }}

// MCP tool descriptors. Each pairs a schema with a tool name and description
// so that LLM clients can discover and invoke the underlying RPCs.
var (
{{- range $key, $val := .SchemaJSON }}
	{{ $key }}Tool = mcpruntime.MustCreateTool("{{ (index $.ToolMeta $key).Name }}", {{ safeRawString (index $.ToolMeta $key).Description }}, {{ $key }}SchemaJSON)
{{- end }}
)

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPServer is the interface that users implement to handle MCP
// tool calls backed by {{ $svcName }} RPCs. Unary RPCs take (ctx, req) and
// return (resp, error). Server-streaming RPCs (with MCPProgress) take (req,
// stream) matching the gRPC server interface — any type implementing
// {{ $svcName }}Server automatically satisfies this interface.
type {{ $svcName }}MCPServer interface {
{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{{ $methName }}(req *{{ $tool.RequestType }}, stream {{ $tool.StreamProgress.StreamServerType }}) error
{{- else }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}) (*{{ $tool.ResponseType }}, error)
{{- end }}
{{- end }}
}

// {{ $svcName }}MCPClient is the gRPC client interface used when forwarding MCP
// tool calls to a remote gRPC server. It matches the generated gRPC client stub.
type {{ $svcName }}MCPClient interface {
{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) ({{ $tool.StreamProgress.StreamClientType }}, error)
{{- else }}
	{{ $methName }}(ctx context.Context, req *{{ $tool.RequestType }}, opts ...grpc.CallOption) (*{{ $tool.ResponseType }}, error)
{{- end }}
{{- end }}
}
{{- end }}

{{- /* ================================================================== */}}
{{- /* RegisterHandler                                                     */}}
{{- /* ================================================================== */}}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// Register{{ $svcName }}MCPHandler registers all {{ $svcName }} RPC methods as MCP
// tools, prompts, resources, and apps on the given server based on proto options.
func Register{{ $svcName }}MCPHandler(s *mcp.Server, srv {{ $svcName }}MCPServer, opts ...mcpruntime.Option) {
	cfg := mcpruntime.ApplyOptions(opts...)
	_ = cfg
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := mcpruntime.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
{{- if $tool.StreamProgress }}
	{
		tool := mcpruntime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcpruntime.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcpruntime.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
			elicitResult, elicitPending, elicitErr := mcpruntime.RunElicitation(req, "{{ $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
				return mcpruntime.TextResult("Action cancelled by user."), nil
			}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcpruntime.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			args = mcpruntime.MergeElicitResult(args, elicitResult.Content, elicitFields)
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			token := req.Params.GetProgressToken()
			session := req.Session
			// notifCtx is unbound so progress notifications are not tied to the
			// tool-call request lifetime.
			// grpcCtx detaches from the tool-call cancellation so the gRPC
			// server method can complete its stream after the HTTP response is sent.
			notifCtx := context.Background()
			grpcCtx := mcpruntime.WithIncomingProgressToken(context.WithoutCancel(ctx), token)
			stream := mcpruntime.NewInProcessServerStream[*{{ $tool.StreamProgress.StreamChunkType }}](grpcCtx)
			errCh := make(chan error, 1)
			go func() {
				defer stream.Close()
				// Streaming tools call the service directly: cfg.UnaryInterceptor
				// is unary-only (a grpc.StreamServerInterceptor has a different
				// shape), so unary middleware does not cover progress tools.
				errCh <- srv.{{ $methName }}(&pbReq, stream)
			}()
			go func() {
				for {
					chunk, ok := stream.Recv()
					if !ok {
						if err := <-errCh; err != nil {
							_ = mcpruntime.SendDoneProgress(notifCtx, session, token, fmt.Sprintf(`{"error":%q}`, err.Error()))
						}
						return
					}
					switch {
					case chunk.Get{{ $tool.StreamProgress.ProgressField }}() != nil:
						_ = mcpruntime.SendProgressFromProto(notifCtx, session, token, chunk.Get{{ $tool.StreamProgress.ProgressField }}())
					case chunk.Get{{ $tool.StreamProgress.ResultField }}() != nil:
						out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(chunk.Get{{ $tool.StreamProgress.ResultField }}())
						if err != nil {
							_ = mcpruntime.SendDoneProgress(notifCtx, session, token, fmt.Sprintf(`{"error":%q}`, err.Error()))
						} else {
							_ = mcpruntime.SendDoneProgress(notifCtx, session, token, string(out))
						}
						return
					}
				}
			}()
			return mcpruntime.TextResult(`{"status":"started"}`), nil
		})
	}
{{- else }}
	{
		tool := mcpruntime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcpruntime.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcpruntime.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
			elicitResult, elicitPending, elicitErr := mcpruntime.RunElicitation(req, "{{ $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
				return mcpruntime.TextResult("Action cancelled by user."), nil
			}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcpruntime.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			args = mcpruntime.MergeElicitResult(args, elicitResult.Content, elicitFields)
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			// Dispatch through the unary interceptor chain (when configured) so
			// middleware sees this call exactly as it would the wire RPC.
			rawResp, err := mcpruntime.InvokeUnary(ctx, cfg.UnaryInterceptor, "{{ $tool.FullMethod }}", srv, &pbReq, func(ctx context.Context, req any) (any, error) {
				return srv.{{ $methName }}(ctx, req.(*{{ $tool.RequestType }}))
			})
			if err != nil {
				return mcpruntime.HandleError(err)
			}
			resp := rawResp.(*{{ $tool.ResponseType }})
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return mcpruntime.TextResult(string(out)), nil
		})
	}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ .URI }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, mcpruntime.DefaultResourceHandler())
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ .URITemplate }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, mcpruntime.DefaultResourceHandler())
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, mcpruntime.DefaultPromptHandler("{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"))
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, mcpruntime.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}"))
{{- end }}
}
{{- end }}

{{- range $svcName, $methods := .Services }}

// {{ $svcName }}MCPDefaultBasePath is the default HTTP path prefix for
// {{ $svcName }} MCP endpoints, derived from the protobuf package and service name.
const {{ $svcName }}MCPDefaultBasePath = "{{ index $.ServiceBasePaths $svcName }}"
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// {{ $svcName }}CompletionMap returns a map of "promptName:argName" → allowed
// values, built from enum_values declared in the proto MCP options.
func {{ $svcName }}CompletionMap() map[string][]string {
	m := map[string][]string{}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
{{- $pName := $tool.MethodOpts.Prompt.Name }}
{{- range $tool.MethodOpts.Prompt.Arguments }}
{{- if .EnumValues }}
	m["{{ $pName }}:{{ .Name }}"] = []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
	return m
}

// Serve{{ $svcName }}MCP creates an MCP server, registers the service tools, and
// starts serving using the configured transport (streamable-http, sse, or stdio).
// Uses the proto-derived BasePath. This is a blocking call.
func Serve{{ $svcName }}MCP(ctx context.Context, srv {{ $svcName }}MCPServer, cfg *mcpruntime.MCPServerConfig, opts ...mcpruntime.Option) error {
	// Set the proto-derived path as the generated default
	cfg.GeneratedBasePath = {{ $svcName }}MCPDefaultBasePath

	// Wire completion handler for prompt arguments with enum_values.
	completionMap := {{ $svcName }}CompletionMap()
	if len(completionMap) > 0 {
		if cfg.ServerOptions == nil {
			cfg.ServerOptions = &mcp.ServerOptions{}
		}
		cfg.ServerOptions.CompletionHandler = mcpruntime.CompletionHandlerFromEnums(completionMap)
	}

	// Forward the hosting server's unary interceptor chain so every tool call
	// runs the same middleware (validation, auth, tracing) as the wire RPC.
	if cfg.UnaryInterceptor != nil {
		opts = append(opts, mcpruntime.WithUnaryInterceptor(cfg.UnaryInterceptor))
	}

	return mcpruntime.StartServer(ctx, cfg, func(s *mcp.Server) {
		Register{{ $svcName }}MCPHandler(s, srv, opts...)
	})
}
{{- end }}

{{- range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}

// ForwardTo{{ $svcName }}MCPClient registers all {{ $svcName }} tools, prompts,
// resources, and apps on the MCP server, forwarding every tool call to a
// remote gRPC server via the provided client stub.
func ForwardTo{{ $svcName }}MCPClient(s *mcp.Server, client {{ $svcName }}MCPClient, opts ...mcpruntime.Option) {
	cfg := mcpruntime.ApplyOptions(opts...)
	_ = cfg
{{- if and $svcOpts $svcOpts.App }}
	appResourceURI := mcpruntime.AppResourceURI("{{ $svcName }}")
{{- end }}

{{- range $methName, $tool := $methods }}
	{
		tool := mcpruntime.PrepareToolWithExtras({{ $svcName }}_{{ $methName }}Tool, cfg.ExtraProperties)
{{- if and $svcOpts $svcOpts.App }}
		tool = mcpruntime.SetToolAppMeta(tool, appResourceURI)
{{- end }}
		s.AddTool(tool, func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			elicitFields := []mcpruntime.ElicitField{
			{{- range $tool.MethodOpts.Elicitation.Fields }}
				{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}, Type: "{{ .Type }}"{{- if .EnumValues }}, EnumValues: []string{ {{- range .EnumValues }}"{{ . }}", {{ end }}}{{- end }}{{- if .EnumProtoNames }}, ProtoValues: []string{ {{- range .EnumProtoNames }}"{{ . }}", {{ end }}}{{- end }}},
			{{- end }}
			}
			if cfg.ElicitHook != nil {
				var hookErr error
				elicitFields, hookErr = cfg.ElicitHook(ctx, {{ $svcName }}_{{ $methName }}Tool.Name, elicitFields)
				if hookErr != nil {
					return nil, hookErr
				}
			}
			// Elicitation is a multi round-trip request (SEP-2322): the first
			// pass returns a pending result asking the client for input, and
			// the client retries the call with the answer, so this handler
			// body runs twice.
			elicitResult, elicitPending, elicitErr := mcpruntime.RunElicitation(req, "{{ $tool.MethodOpts.Elicitation.Message }}", elicitFields)
			if elicitErr != nil {
				return nil, elicitErr
			}
			if elicitPending != nil {
				return elicitPending, nil
			}
			if elicitResult.Action != "accept" {
				return mcpruntime.TextResult("Action cancelled by user."), nil
			}
{{- end }}
			var pbReq {{ $tool.RequestType }}
			args, ctx := mcpruntime.ExtractExtras(ctx, req.Params.Arguments, cfg)
{{- if and $tool.MethodOpts $tool.MethodOpts.Elicitation }}
			args = mcpruntime.MergeElicitResult(args, elicitResult.Content, elicitFields)
{{- end }}
			if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(args, &pbReq); err != nil {
				return nil, err
			}
			ctx = mcpruntime.ForwardMetadata(ctx)
{{- if $tool.StreamProgress }}
			if token := req.Params.GetProgressToken(); token != nil {
				ctx = mcpruntime.WithProgressToken(ctx, token)
			}
			stream, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return mcpruntime.HandleError(err)
			}
			token := req.Params.GetProgressToken()
			for {
				chunk, err := stream.Recv()
				if err != nil {
					if errors.Is(err, context.Canceled) {
						return nil, err
					}
					return mcpruntime.HandleError(err)
				}
				switch {
				case chunk.Get{{ $tool.StreamProgress.ProgressField }}() != nil:
					_ = mcpruntime.SendProgressFromProto(ctx, req.Session, token, chunk.Get{{ $tool.StreamProgress.ProgressField }}())
				case chunk.Get{{ $tool.StreamProgress.ResultField }}() != nil:
					out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(chunk.Get{{ $tool.StreamProgress.ResultField }}())
					if err != nil {
						return nil, err
					}
					return mcpruntime.TextResult(string(out)), nil
				}
			}
{{- else }}
			resp, err := client.{{ $methName }}(ctx, &pbReq)
			if err != nil {
				return mcpruntime.HandleError(err)
			}
			out, err := (protojson.MarshalOptions{UseProtoNames: true, EmitDefaultValues: true}).Marshal(resp)
			if err != nil {
				return nil, err
			}
			return mcpruntime.TextResult(string(out)), nil
{{- end }}
		})
	}
{{- end }}
{{- if and $svcOpts $svcOpts.Resources }}

{{- range $svcOpts.Resources }}
{{- if .URI }}
	s.AddResource(&mcp.Resource{
		URI:         "{{ .URI }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, mcpruntime.DefaultResourceHandler())
{{- end }}
{{- if .URITemplate }}
	s.AddResourceTemplate(&mcp.ResourceTemplate{
		URITemplate: "{{ .URITemplate }}",
		Name:        "{{ .Name }}",
		Description: "{{ .Description }}",
		MIMEType:    "{{ .MimeType }}",
	}, mcpruntime.DefaultResourceHandler())
{{- end }}
{{- end }}
{{- end }}
{{- $hasMethodPrompts := false }}
{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}{{ $hasMethodPrompts = true }}{{ end }}
{{- end }}
{{- if $hasMethodPrompts }}

{{- range $methName, $tool := $methods }}
{{- if and $tool.MethodOpts $tool.MethodOpts.Prompt }}
	s.AddPrompt(&mcp.Prompt{
		Name:        "{{ $tool.MethodOpts.Prompt.Name }}",
		Description: "{{ $tool.MethodOpts.Prompt.Description }}",
		Arguments: []*mcp.PromptArgument{
		{{- range $tool.MethodOpts.Prompt.Arguments }}
			{Name: "{{ .Name }}", Description: "{{ escapeQuotes .Description }}", Required: {{ .Required }}},
		{{- end }}
		},
	}, mcpruntime.DefaultPromptHandler("{{ escapeQuotes $tool.MethodOpts.Prompt.Description }}"))
{{- end }}
{{- end }}
{{- end }}
{{- if and $svcOpts $svcOpts.App }}

	s.AddResource(&mcp.Resource{
		URI:      appResourceURI,
		Name:     "{{ escapeQuotes $svcOpts.App.Name }}",
		MIMEType: "text/html",
	}, mcpruntime.DefaultAppResourceHandler("{{ escapeQuotes $svcOpts.App.Name }}", "{{ $svcOpts.App.Version }}", "{{ escapeQuotes $svcOpts.App.Description }}"))
{{- end }}
}
{{- end }}
