// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
// 	protoc-gen-mcp {{ .Version }}
// Authors: The Protobuf Project - Open Source 2026
// source: {{ .SourcePath }}

use std::sync::Arc;
use async_trait::async_trait;
use rmcp::{ErrorData as McpError, RoleServer, ServerHandler, ServiceExt, model::*, service::RequestContext};
use serde_json::{self, json, Value};

fn make_tool(name: &str, description: &str, schema_json: &str) -> Tool {
    serde_json::from_value(json!({
        "name": name, "description": description,
        "inputSchema": serde_json::from_str::<Value>(schema_json).unwrap(),
    })).expect("generated tool schema must be valid")
}

fn make_tool_with_app_meta(name: &str, description: &str, schema_json: &str, app_resource_uri: &str) -> Tool {
    serde_json::from_value(json!({
        "name": name, "description": description,
        "inputSchema": serde_json::from_str::<Value>(schema_json).unwrap(),
        "_meta": { "ui": { "resourceUri": app_resource_uri } }
    })).expect("generated tool schema must be valid")
}

fn app_resource_uri(service_name: &str) -> String {
    format!("ui://{}/app.html", service_name.to_lowercase())
}

fn default_app_html(app_name: &str, version: &str, description: &str) -> String {
    format!("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>{app_name}</title></head><body><h1>{app_name}</h1><p>v{version}</p><p>{description}</p><p>This is a generated MCP App placeholder. Replace this resource with your own UI.</p></body></html>")
}
{{ range $svcName, $methods := .Services }}
{{- $svcOpts := index $.ServiceOpts $svcName }}
{{- $hasResources := false }}
{{- if and $svcOpts $svcOpts.Resources }}{{ $hasResources = true }}{{ end }}
{{- if and $svcOpts $svcOpts.App }}{{ $hasResources = true }}{{ end }}
{{- range $methName, $info := $methods }}
const {{ $info.ConstName }}_SCHEMA_JSON: &str = r##"{{ index $.SchemaJSON (printf "%s_%s" $svcName $methName) }}"##;
{{- end }}

#[async_trait]
pub trait {{ $svcName }}McpServer: Send + Sync + 'static {
{{- range $methName, $info := $methods }}
{{- if not $info.StreamProgress }}
    async fn {{ $info.RsMethodName }}(&self, args: Value) -> std::result::Result<Value, McpError>;
{{- end }}
{{- end }}
}

pub struct {{ $svcName }}McpHandler<T: {{ $svcName }}McpServer> { inner: Arc<T> }

impl<T: {{ $svcName }}McpServer> Clone for {{ $svcName }}McpHandler<T> {
    fn clone(&self) -> Self { Self { inner: Arc::clone(&self.inner) } }
}

impl<T: {{ $svcName }}McpServer> {{ $svcName }}McpHandler<T> {
    pub fn new(svc: T) -> Self { Self { inner: Arc::new(svc) } }

    pub fn tools() -> Vec<Tool> {
{{- if and $svcOpts $svcOpts.App }}
        let app_uri = app_resource_uri("{{ $svcName }}");
{{- end }}
        vec![
        {{- range $methName, $info := $methods }}
        {{- if not $info.StreamProgress }}
{{- if and $svcOpts $svcOpts.App }}
            make_tool_with_app_meta("{{ $info.ToolName }}", "{{ $info.Description | rsEscape }}", {{ $info.ConstName }}_SCHEMA_JSON, &app_uri),
{{- else }}
            make_tool("{{ $info.ToolName }}", "{{ $info.Description | rsEscape }}", {{ $info.ConstName }}_SCHEMA_JSON),
{{- end }}
        {{- end }}
        {{- end }}
        ]
    }

    pub fn all_tools() -> Vec<Tool> {
{{- if and $svcOpts $svcOpts.App }}
        let app_uri = app_resource_uri("{{ $svcName }}");
{{- end }}
        vec![
        {{- range $methName, $info := $methods }}
{{- if and $svcOpts $svcOpts.App }}
            make_tool_with_app_meta("{{ $info.ToolName }}", "{{ $info.Description | rsEscape }}", {{ $info.ConstName }}_SCHEMA_JSON, &app_uri),
{{- else }}
            make_tool("{{ $info.ToolName }}", "{{ $info.Description | rsEscape }}", {{ $info.ConstName }}_SCHEMA_JSON),
{{- end }}
        {{- end }}
        ]
    }
{{- $hasPrompts := false }}
{{- $hasPromptCompletions := false }}
{{- range $methName, $info := $methods }}
{{- if and $info.MethodOpts $info.MethodOpts.Prompt }}{{ $hasPrompts = true }}{{ end }}
{{- if and $info.MethodOpts $info.MethodOpts.Prompt }}
{{- range $info.MethodOpts.Prompt.Arguments }}
{{- if .EnumValues }}{{ $hasPromptCompletions = true }}{{ end }}
{{- end }}
{{- end }}
{{- end }}
{{- if $hasPrompts }}

    pub fn prompts() -> Vec<Prompt> {
        vec![
        {{- range $methName, $info := $methods }}
        {{- if and $info.MethodOpts $info.MethodOpts.Prompt }}
            serde_json::from_value(json!({
                "name": "{{ $info.MethodOpts.Prompt.Name }}",
                "description": "{{ $info.MethodOpts.Prompt.Description | rsEscape }}",
                "arguments": [
                {{- range $info.MethodOpts.Prompt.Arguments }}
                    {"name": "{{ .Name }}", "description": "{{ .Description | rsEscape }}", "required": {{ if .Required }}true{{ else }}false{{ end }}},
                {{- end }}
                ]
            })).expect("generated prompt must be valid"),
        {{- end }}
        {{- end }}
        ]
    }
{{- end }}
{{- if $hasPromptCompletions }}

    pub fn completion_map() -> std::collections::HashMap<String, Vec<String>> {
        let mut m: std::collections::HashMap<String, Vec<String>> = std::collections::HashMap::new();
{{- range $methName, $info := $methods }}
{{- if and $info.MethodOpts $info.MethodOpts.Prompt }}
{{- $pName := $info.MethodOpts.Prompt.Name }}
{{- range $info.MethodOpts.Prompt.Arguments }}
{{- if .EnumValues }}
        m.insert(
            "{{ $pName }}:{{ .Name }}".to_string(),
            vec![{{- range .EnumValues }}"{{ . }}".to_string(), {{- end }}],
        );
{{- end }}
{{- end }}
{{- end }}
{{- end }}
        m
    }
{{- end }}
{{- if $hasResources }}

    pub fn resources() -> Vec<Resource> {
        vec![
        {{- range $svcOpts.Resources }}
        {{- if .URI }}
            serde_json::from_value(json!({
                "uri": "{{ .URI }}", "name": "{{ .Name }}",
                {{- if .Title }}
                "title": "{{ .Title | rsEscape }}",
                {{- end }}
                {{- if .HasSize }}
                "size": {{ .Size }},
                {{- end }}
                {{- template "rsResourceExtras" . }}
                "description": "{{ .Description | rsEscape }}", "mimeType": "{{ .MimeType }}"
            })).expect("generated resource must be valid"),
        {{- end }}
        {{- end }}
        {{- if and $svcOpts $svcOpts.App }}
            serde_json::from_value(json!({
                "uri": app_resource_uri("{{ $svcName }}"),
                "name": "{{ $svcOpts.App.Name }}",
                "mimeType": "text/html"
            })).expect("generated app resource must be valid"),
        {{- end }}
        ]
    }

    pub fn resource_templates() -> Vec<ResourceTemplate> {
        vec![
        {{- range $svcOpts.Resources }}
        {{- if .URITemplate }}
            serde_json::from_value(json!({
                "uriTemplate": "{{ .URITemplate }}", "name": "{{ .Name }}",
                {{- if .Title }}
                "title": "{{ .Title | rsEscape }}",
                {{- end }}
                {{- template "rsResourceExtras" . }}
                "description": "{{ .Description | rsEscape }}", "mimeType": "{{ .MimeType }}"
            })).expect("generated resource template must be valid"),
        {{- end }}
        {{- end }}
        ]
    }
{{- end }}
}

impl<T: {{ $svcName }}McpServer> ServerHandler for {{ $svcName }}McpHandler<T> {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
{{- if $hasPrompts }}
                .enable_prompts()
{{- end }}
{{- if $hasPromptCompletions }}
                .enable_completions()
{{- end }}
{{- if $hasResources }}
                .enable_resources()
{{- end }}
                .build(),
        )
        .with_server_info(Implementation::new("{{ $svcName }}", "0.1.0"))
    }

    async fn list_tools(&self, _: Option<PaginatedRequestParams>, _: RequestContext<RoleServer>) -> std::result::Result<ListToolsResult, McpError> {
        Ok(ListToolsResult::with_all_items(Self::tools()))
    }

{{- /* context is only read to raise an elicitation, so bind it as unused when
       no method on this service declares one — generated code must not warn. */}}
{{- $usesContext := false }}
{{- range $methName, $info := $methods }}
{{- if and $info.MethodOpts $info.MethodOpts.Elicitation }}{{ $usesContext = true }}{{ end }}
{{- end }}
    async fn call_tool(&self, request: CallToolRequestParams, {{ if $usesContext }}context{{ else }}_context{{ end }}: RequestContext<RoleServer>) -> std::result::Result<CallToolResponse, McpError> {
        let args = request.arguments.map_or_else(|| Value::Object(Default::default()), Value::Object);
        match request.name.as_ref() {
        {{- range $methName, $info := $methods }}
        {{- if not $info.StreamProgress }}
            "{{ $info.ToolName }}" => {
{{- if and $info.MethodOpts $info.MethodOpts.Elicitation }}
                if let Ok(schema) = ElicitationSchema::from_json_schema(
                    serde_json::from_value(json!({
                        "type": "object",
                        "properties": {
                        {{- range $info.MethodOpts.Elicitation.Fields }}
                            "{{ .Name }}": {"type": "{{ .Type }}", "description": "{{ .Description }}"{{ if .EnumValues }}, "enum": [{{ range .EnumValues }}"{{ . }}", {{ end }}]{{ end }}},
                        {{- end }}
                        },
                        "required": [{{ range $info.MethodOpts.Elicitation.Fields }}{{ if .Required }}"{{ .Name }}", {{ end }}{{ end }}]
                    })).unwrap()
                ) {
                    let params = ElicitRequestParams::FormElicitationParams {
                        meta: None,
                        message: {{ $info.MethodOpts.Elicitation.Message | printf "%q" }}.to_string(),
                        requested_schema: schema,
                    };
                    match context.peer.create_elicitation(params).await {
                        Ok(result) if result.action != ElicitationAction::Accept => {
                            return Ok(CallToolResult::success(vec![ContentBlock::text("Action cancelled by user.")]).into());
                        }
                        _ => {} // proceed (including errors — graceful degradation)
                    }
                }
{{- end }}
                let result = self.inner.{{ $info.RsMethodName }}(args).await?;
                let text = serde_json::to_string(&result)
                    .map_err(|e| McpError::internal_error(format!("serialize response: {e}"), None))?;
                Ok(CallToolResult::success(vec![ContentBlock::text(text)]).into())
            }
        {{- end }}
        {{- end }}
            _ => Err(McpError::internal_error(format!("unknown tool: {}", request.name), None)),
        }
    }
{{- if $hasPrompts }}

    async fn list_prompts(&self, _: Option<PaginatedRequestParams>, _: RequestContext<RoleServer>) -> std::result::Result<ListPromptsResult, McpError> {
        Ok(ListPromptsResult::with_all_items(Self::prompts()))
    }

    async fn get_prompt(&self, request: GetPromptRequestParams, _: RequestContext<RoleServer>) -> std::result::Result<GetPromptResponse, McpError> {
        for p in Self::prompts() {
            if p.name == request.name {
                let arg_str: String = request.arguments.as_ref()
                    .map(|a| a.iter().map(|(k, v)| format!("{k}={v}")).collect::<Vec<_>>().join(", "))
                    .unwrap_or_default();
                let desc = p.description.clone().unwrap_or_default();
                let messages = vec![PromptMessage::new_text(Role::User, format!("{desc} ({arg_str})"))];
                let mut result = GetPromptResult::new(messages);
                if let Some(ref d) = p.description {
                    result = result.with_description(d.clone());
                }
                return Ok(result.into());
            }
        }
        Err(McpError::invalid_params(format!("unknown prompt: {}", request.name), None))
    }
{{- end }}
{{- if $hasPromptCompletions }}

    async fn complete(&self, request: CompleteRequestParams, _: RequestContext<RoleServer>) -> std::result::Result<CompleteResult, McpError> {
        let key = match request.r#ref {
            Reference::Prompt(prompt_ref) => format!("{}:{}", prompt_ref.name, request.argument.name),
            _ => {
                let completion = CompletionInfo::with_all_values(Vec::new())
                    .map_err(|e| McpError::internal_error(format!("completion error: {e}"), None))?;
                return Ok(CompleteResult::new(completion));
            }
        };
        let values = Self::completion_map().get(&key).cloned().unwrap_or_default();
        let prefix = request.argument.value.to_lowercase();
        let filtered: Vec<String> = values
            .into_iter()
            .filter(|v| v.to_lowercase().starts_with(&prefix))
            .collect();
        let completion = CompletionInfo::with_all_values(filtered)
            .map_err(|e| McpError::internal_error(format!("completion error: {e}"), None))?;
        Ok(CompleteResult::new(completion))
    }
{{- end }}
{{- if $hasResources }}

    async fn list_resources(&self, _: Option<PaginatedRequestParams>, _: RequestContext<RoleServer>) -> std::result::Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult::with_all_items(Self::resources()))
    }

    async fn list_resource_templates(&self, _: Option<PaginatedRequestParams>, _: RequestContext<RoleServer>) -> std::result::Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult::with_all_items(Self::resource_templates()))
    }

    async fn read_resource(&self, request: ReadResourceRequestParams, _: RequestContext<RoleServer>) -> std::result::Result<ReadResourceResponse, McpError> {
{{- if and $svcOpts $svcOpts.App }}
        let app_uri = app_resource_uri("{{ $svcName }}");
        if request.uri == app_uri {
            let html = default_app_html("{{ $svcOpts.App.Name | rsEscape }}", "{{ $svcOpts.App.Version }}", "{{ $svcOpts.App.Description | rsEscape }}");
            return Ok(ReadResourceResult::new(vec![
                ResourceContents::text(html, request.uri).with_mime_type("text/html")
            ]).into());
        }
{{- end }}
        Ok(ReadResourceResult::new(vec![ResourceContents::text("{}", request.uri)]).into())
    }
{{- end }}
}

pub const {{ $svcName | screamingSnakeCase }}_MCP_DEFAULT_BASE_PATH: &str = "{{ index $.ServiceBasePaths $svcName }}";

pub struct {{ $svcName }}McpTransportConfig {
    pub transport: String,
    pub host: String,
    pub port: u16,
    pub base_path: String,
}

impl Default for {{ $svcName }}McpTransportConfig {
    fn default() -> Self {
        Self { transport: "streamable-http".into(), host: "0.0.0.0".into(), port: 8080,
               base_path: {{ $svcName | screamingSnakeCase }}_MCP_DEFAULT_BASE_PATH.into() }
    }
}

pub async fn serve_{{ $svcName | snakeCase }}_mcp_stdio<T: {{ $svcName }}McpServer>(svc: T) -> std::result::Result<(), Box<dyn std::error::Error>> {
    let handler = {{ $svcName }}McpHandler::new(svc);
    handler.serve(rmcp::transport::stdio()).await?.waiting().await?;
    Ok(())
}

pub async fn serve_{{ $svcName | snakeCase }}_mcp<T: {{ $svcName }}McpServer>(
    svc: T, config: {{ $svcName }}McpTransportConfig,
) -> std::result::Result<(), Box<dyn std::error::Error>> {
    let handler = {{ $svcName }}McpHandler::new(svc);
    let transports: Vec<&str> = config.transport.split(',').map(|s| s.trim()).filter(|s| !s.is_empty()).collect();
    let has_stdio = transports.iter().any(|t| *t == "stdio");
    let http_transport = transports.iter().find(|t| **t == "sse" || **t == "streamable-http").copied();

    if let Some(_ht) = http_transport {
        use rmcp::transport::streamable_http_server::{
            StreamableHttpServerConfig, StreamableHttpService, session::local::LocalSessionManager,
        };
        let h = handler.clone();
        let http_config = StreamableHttpServerConfig::default().with_sse_retry(None);
        let http_service = StreamableHttpService::new(
            move || Ok(h.clone()), Arc::new(LocalSessionManager::default()),
            http_config,
        );
        let app = axum::Router::new().nest_service(&config.base_path, http_service);
        let addr = format!("{}:{}", config.host, config.port);
        let listener = tokio::net::TcpListener::bind(&addr).await?;
        if has_stdio {
            tokio::spawn(async move { axum::serve(listener, app).await.expect("HTTP server failed"); });
        } else {
            axum::serve(listener, app).await?;
            return Ok(());
        }
    }

    if has_stdio {
        handler.serve(rmcp::transport::stdio()).await?.waiting().await?;
    } else if http_transport.is_none() {
        return Err(format!("unsupported transport(s): {}", config.transport).into());
    }
    Ok(())
}
{{- end }}

{{- define "rsResourceExtras" }}
{{- with .Annotations }}
                "annotations": {
                    {{- if .Audience }}
                    "audience": [{{ range $i, $a := .Audience }}{{ if $i }}, {{ end }}"{{ $a }}"{{ end }}],
                    {{- end }}
                    {{- if .LastModified }}
                    "lastModified": "{{ .LastModified }}",
                    {{- end }}
                    {{- if .HasPriority }}
                    "priority": {{ .Priority }}
                    {{- end }}
                },
{{- end }}
{{- if .Icons }}
                "icons": [
                    {{- range .Icons }}
                    {"src": "{{ .Src }}"{{ if .MimeType }}, "mimeType": "{{ .MimeType }}"{{ end }}{{ if .Sizes }}, "sizes": [{{ range $j, $s := .Sizes }}{{ if $j }}, {{ end }}"{{ $s }}"{{ end }}]{{ end }}{{ if .Theme }}, "theme": "{{ .Theme }}"{{ end }}},
                    {{- end }}
                ],
{{- end }}
{{- end }}
