// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/app.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPApp describes application-level metadata for an MCP server.
type MCPApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display name of the MCP application.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The version of the MCP application (e.g. "1.0.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// A human-readable description of the MCP application.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPApp) Reset() {
	*x = MCPApp{}
	mi := &file_mcp_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPApp) ProtoMessage() {}

func (x *MCPApp) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPApp.ProtoReflect.Descriptor instead.
func (*MCPApp) Descriptor() ([]byte, []int) {
	return file_mcp_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *MCPApp) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MCPApp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MCPApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_mcp_v1_app_proto protoreflect.FileDescriptor

const file_mcp_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x10mcp/v1/app.proto\x12\x06mcp.v1\"g\n" +
	"\x06MCPApp\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionBL\n" +
	"\n" +
	"com.mcp.v1B\bAppProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_app_proto_rawDescOnce sync.Once
	file_mcp_v1_app_proto_rawDescData []byte
)

func file_mcp_v1_app_proto_rawDescGZIP() []byte {
	file_mcp_v1_app_proto_rawDescOnce.Do(func() {
		file_mcp_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_app_proto_rawDesc), len(file_mcp_v1_app_proto_rawDesc)))
	})
	return file_mcp_v1_app_proto_rawDescData
}

var file_mcp_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_app_proto_goTypes = []any{
	(*MCPApp)(nil), // 0: mcp.v1.MCPApp
}
var file_mcp_v1_app_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_v1_app_proto_init() }
func file_mcp_v1_app_proto_init() {
	if File_mcp_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_app_proto_rawDesc), len(file_mcp_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_app_proto_goTypes,
		DependencyIndexes: file_mcp_v1_app_proto_depIdxs,
		MessageInfos:      file_mcp_v1_app_proto_msgTypes,
	}.Build()
	File_mcp_v1_app_proto = out.File
	file_mcp_v1_app_proto_goTypes = nil
	file_mcp_v1_app_proto_depIdxs = nil
}
