// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/app.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPApp describes application-level metadata for an MCP server.
type MCPApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The display name of the MCP application.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The version of the MCP application (e.g. "1.0.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// A human-readable description of the MCP application.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Display name preferred over display_name in UI and end-user contexts.
	Title *string `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Website for the server, shown by clients that surface one.
	WebsiteUrl *string `protobuf:"bytes,5,opt,name=website_url,json=websiteUrl,proto3,oneof" json:"website_url,omitempty"`
	// Icons representing the server in client UIs.
	Icons         []*MCPIcon `protobuf:"bytes,6,rep,name=icons,proto3" json:"icons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPApp) Reset() {
	*x = MCPApp{}
	mi := &file_mcp_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPApp) ProtoMessage() {}

func (x *MCPApp) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPApp.ProtoReflect.Descriptor instead.
func (*MCPApp) Descriptor() ([]byte, []int) {
	return file_mcp_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *MCPApp) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MCPApp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MCPApp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPApp) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MCPApp) GetWebsiteUrl() string {
	if x != nil && x.WebsiteUrl != nil {
		return *x.WebsiteUrl
	}
	return ""
}

func (x *MCPApp) GetIcons() []*MCPIcon {
	if x != nil {
		return x.Icons
	}
	return nil
}

var File_mcp_v1_app_proto protoreflect.FileDescriptor

const file_mcp_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x10mcp/v1/app.proto\x12\x06mcp.v1\x1a\x11mcp/v1/icon.proto\"\xe9\x01\n" +
	"\x06MCPApp\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x00R\x05title\x88\x01\x01\x12$\n" +
	"\vwebsite_url\x18\x05 \x01(\tH\x01R\n" +
	"websiteUrl\x88\x01\x01\x12%\n" +
	"\x05icons\x18\x06 \x03(\v2\x0f.mcp.v1.MCPIconR\x05iconsB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_website_urlBL\n" +
	"\n" +
	"com.mcp.v1B\bAppProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_app_proto_rawDescOnce sync.Once
	file_mcp_v1_app_proto_rawDescData []byte
)

func file_mcp_v1_app_proto_rawDescGZIP() []byte {
	file_mcp_v1_app_proto_rawDescOnce.Do(func() {
		file_mcp_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_app_proto_rawDesc), len(file_mcp_v1_app_proto_rawDesc)))
	})
	return file_mcp_v1_app_proto_rawDescData
}

var file_mcp_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_app_proto_goTypes = []any{
	(*MCPApp)(nil),  // 0: mcp.v1.MCPApp
	(*MCPIcon)(nil), // 1: mcp.v1.MCPIcon
}
var file_mcp_v1_app_proto_depIdxs = []int32{
	1, // 0: mcp.v1.MCPApp.icons:type_name -> mcp.v1.MCPIcon
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_v1_app_proto_init() }
func file_mcp_v1_app_proto_init() {
	if File_mcp_v1_app_proto != nil {
		return
	}
	file_mcp_v1_icon_proto_init()
	file_mcp_v1_app_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_app_proto_rawDesc), len(file_mcp_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_app_proto_goTypes,
		DependencyIndexes: file_mcp_v1_app_proto_depIdxs,
		MessageInfos:      file_mcp_v1_app_proto_msgTypes,
	}.Build()
	File_mcp_v1_app_proto = out.File
	file_mcp_v1_app_proto_goTypes = nil
	file_mcp_v1_app_proto_depIdxs = nil
}
