// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/cache.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPCacheScope mirrors HTTP Cache-Control's public/private distinction.
type MCPCacheScope int32

const (
	// No scope stated. Clients default this to public, so declare
	// MCP_CACHE_SCOPE_PRIVATE explicitly for anything user-specific.
	MCPCacheScope_MCP_CACHE_SCOPE_UNSPECIFIED MCPCacheScope = 0
	// Any client or intermediary may cache the response and serve it to any
	// user. Correct only when the response is identical for every caller.
	MCPCacheScope_MCP_CACHE_SCOPE_PUBLIC MCPCacheScope = 1
	// Only the requesting user's client may cache the response. Use this
	// whenever the result depends on who asked — a shared cache holding a
	// per-user response leaks it across tenants.
	MCPCacheScope_MCP_CACHE_SCOPE_PRIVATE MCPCacheScope = 2
)

// Enum value maps for MCPCacheScope.
var (
	MCPCacheScope_name = map[int32]string{
		0: "MCP_CACHE_SCOPE_UNSPECIFIED",
		1: "MCP_CACHE_SCOPE_PUBLIC",
		2: "MCP_CACHE_SCOPE_PRIVATE",
	}
	MCPCacheScope_value = map[string]int32{
		"MCP_CACHE_SCOPE_UNSPECIFIED": 0,
		"MCP_CACHE_SCOPE_PUBLIC":      1,
		"MCP_CACHE_SCOPE_PRIVATE":     2,
	}
)

func (x MCPCacheScope) Enum() *MCPCacheScope {
	p := new(MCPCacheScope)
	*p = x
	return p
}

func (x MCPCacheScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPCacheScope) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_cache_proto_enumTypes[0].Descriptor()
}

func (MCPCacheScope) Type() protoreflect.EnumType {
	return &file_mcp_v1_cache_proto_enumTypes[0]
}

func (x MCPCacheScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPCacheScope.Descriptor instead.
func (MCPCacheScope) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_cache_proto_rawDescGZIP(), []int{0}
}

// MCPCacheHint tells clients how long they may cache a list or read result,
// and who may share it. Introduced by MCP protocol revision 2026-07-28, which
// made tools/list, prompts/list, resources/list, resources/templates/list and
// resources/read cacheable.
type MCPCacheHint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How long a client may treat the response as fresh. Semantics match HTTP
	// Cache-Control max-age. Unset or zero means the response is immediately
	// stale, which is also the behavior when no hint is given.
	//
	// A duration rather than a millisecond count: this is an elapsed span, not a
	// point in time, and google.protobuf.Duration is the type protobuf has for
	// that. The generator converts it to the milliseconds MCP puts on the wire.
	Ttl *durationpb.Duration `protobuf:"bytes,1,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	// Who may share the cached response.
	Scope         MCPCacheScope `protobuf:"varint,2,opt,name=scope,proto3,enum=mcp.v1.MCPCacheScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPCacheHint) Reset() {
	*x = MCPCacheHint{}
	mi := &file_mcp_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPCacheHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPCacheHint) ProtoMessage() {}

func (x *MCPCacheHint) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPCacheHint.ProtoReflect.Descriptor instead.
func (*MCPCacheHint) Descriptor() ([]byte, []int) {
	return file_mcp_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *MCPCacheHint) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *MCPCacheHint) GetScope() MCPCacheScope {
	if x != nil {
		return x.Scope
	}
	return MCPCacheScope_MCP_CACHE_SCOPE_UNSPECIFIED
}

var File_mcp_v1_cache_proto protoreflect.FileDescriptor

const file_mcp_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x12mcp/v1/cache.proto\x12\x06mcp.v1\x1a\x1egoogle/protobuf/duration.proto\"u\n" +
	"\fMCPCacheHint\x120\n" +
	"\x03ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\x03ttl\x88\x01\x01\x12+\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x15.mcp.v1.MCPCacheScopeR\x05scopeB\x06\n" +
	"\x04_ttl*i\n" +
	"\rMCPCacheScope\x12\x1f\n" +
	"\x1bMCP_CACHE_SCOPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MCP_CACHE_SCOPE_PUBLIC\x10\x01\x12\x1b\n" +
	"\x17MCP_CACHE_SCOPE_PRIVATE\x10\x02BN\n" +
	"\n" +
	"com.mcp.v1B\n" +
	"CacheProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_cache_proto_rawDescOnce sync.Once
	file_mcp_v1_cache_proto_rawDescData []byte
)

func file_mcp_v1_cache_proto_rawDescGZIP() []byte {
	file_mcp_v1_cache_proto_rawDescOnce.Do(func() {
		file_mcp_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_cache_proto_rawDesc), len(file_mcp_v1_cache_proto_rawDesc)))
	})
	return file_mcp_v1_cache_proto_rawDescData
}

var file_mcp_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_cache_proto_goTypes = []any{
	(MCPCacheScope)(0),          // 0: mcp.v1.MCPCacheScope
	(*MCPCacheHint)(nil),        // 1: mcp.v1.MCPCacheHint
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_mcp_v1_cache_proto_depIdxs = []int32{
	2, // 0: mcp.v1.MCPCacheHint.ttl:type_name -> google.protobuf.Duration
	0, // 1: mcp.v1.MCPCacheHint.scope:type_name -> mcp.v1.MCPCacheScope
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_v1_cache_proto_init() }
func file_mcp_v1_cache_proto_init() {
	if File_mcp_v1_cache_proto != nil {
		return
	}
	file_mcp_v1_cache_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_cache_proto_rawDesc), len(file_mcp_v1_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_cache_proto_goTypes,
		DependencyIndexes: file_mcp_v1_cache_proto_depIdxs,
		EnumInfos:         file_mcp_v1_cache_proto_enumTypes,
		MessageInfos:      file_mcp_v1_cache_proto_msgTypes,
	}.Build()
	File_mcp_v1_cache_proto = out.File
	file_mcp_v1_cache_proto_goTypes = nil
	file_mcp_v1_cache_proto_depIdxs = nil
}
