// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/elicitation.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPElicitationMode selects how the user provides input.
type MCPElicitationMode int32

const (
	// Inferred automatically: FORM if schema is set, URL if url is set.
	MCPElicitationMode_MCP_ELICITATION_MODE_UNSPECIFIED MCPElicitationMode = 0
	// Form-based dialog: a JSON schema built from the attached proto message is
	// shown to the user as a structured input form.
	MCPElicitationMode_MCP_ELICITATION_MODE_FORM MCPElicitationMode = 1
	// URL-based: the user is directed to an external URL to complete input.
	MCPElicitationMode_MCP_ELICITATION_MODE_URL MCPElicitationMode = 2
)

// Enum value maps for MCPElicitationMode.
var (
	MCPElicitationMode_name = map[int32]string{
		0: "MCP_ELICITATION_MODE_UNSPECIFIED",
		1: "MCP_ELICITATION_MODE_FORM",
		2: "MCP_ELICITATION_MODE_URL",
	}
	MCPElicitationMode_value = map[string]int32{
		"MCP_ELICITATION_MODE_UNSPECIFIED": 0,
		"MCP_ELICITATION_MODE_FORM":        1,
		"MCP_ELICITATION_MODE_URL":         2,
	}
)

func (x MCPElicitationMode) Enum() *MCPElicitationMode {
	p := new(MCPElicitationMode)
	*p = x
	return p
}

func (x MCPElicitationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPElicitationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_elicitation_proto_enumTypes[0].Descriptor()
}

func (MCPElicitationMode) Type() protoreflect.EnumType {
	return &file_mcp_v1_elicitation_proto_enumTypes[0]
}

func (x MCPElicitationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPElicitationMode.Descriptor instead.
func (MCPElicitationMode) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_elicitation_proto_rawDescGZIP(), []int{0}
}

// MCPElicitation defines a user-input step shown before a tool executes.
//
// Supports two modes:
//   - Form mode (default): a structured form whose fields come from a proto
//     message type you attach via schema.
//   - URL mode: redirect the user to an external URL for input.
//
// Form mode example:
//
//	option (mcp.v1.elicitation) = {
//	  message: "Please confirm before deleting."
//	  schema: "todo.v1.DeleteConfirmation"
//	};
//
// URL mode example:
//
//	option (mcp.v1.elicitation) = {
//	  mode: ELICITATION_MODE_URL
//	  message: "Complete authentication via the link below."
//	  url: "https://example.com/auth"
//	  elicitation_id: "auth-session-abc"
//	};
type MCPElicitation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message shown to the user (prompt text, e.g. "Are you sure?").
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// [Form mode] Fully-qualified proto message name whose fields define the
	// elicitation form, e.g. "todo.v1.DeleteConfirmation".
	//
	// The generator reads the message descriptor to extract field names, types,
	// descriptions, required-ness, and enum values — no hand-written schema needed.
	Schema string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	// Elicitation mode. When UNSPECIFIED, inferred from other fields:
	//   - FORM if schema is set
	//   - URL  if url is set
	//   - FORM otherwise (no input collected)
	Mode MCPElicitationMode `protobuf:"varint,3,opt,name=mode,proto3,enum=mcp.v1.MCPElicitationMode" json:"mode,omitempty"`
	// [URL mode] External URL the user is directed to for input.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// [URL mode] Unique identifier for this elicitation session, used to
	// correlate the external callback with the in-flight tool call.
	ElicitationId string `protobuf:"bytes,5,opt,name=elicitation_id,json=elicitationId,proto3" json:"elicitation_id,omitempty"`
	// When true, the tool call is aborted if the user declines/cancels or
	// the client does not support elicitation. Default false: elicitation is
	// attempted but failures are silently ignored and the tool proceeds with
	// the original LLM-provided arguments.
	Required      bool `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPElicitation) Reset() {
	*x = MCPElicitation{}
	mi := &file_mcp_v1_elicitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPElicitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPElicitation) ProtoMessage() {}

func (x *MCPElicitation) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_elicitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPElicitation.ProtoReflect.Descriptor instead.
func (*MCPElicitation) Descriptor() ([]byte, []int) {
	return file_mcp_v1_elicitation_proto_rawDescGZIP(), []int{0}
}

func (x *MCPElicitation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MCPElicitation) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *MCPElicitation) GetMode() MCPElicitationMode {
	if x != nil {
		return x.Mode
	}
	return MCPElicitationMode_MCP_ELICITATION_MODE_UNSPECIFIED
}

func (x *MCPElicitation) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MCPElicitation) GetElicitationId() string {
	if x != nil {
		return x.ElicitationId
	}
	return ""
}

func (x *MCPElicitation) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_mcp_v1_elicitation_proto protoreflect.FileDescriptor

const file_mcp_v1_elicitation_proto_rawDesc = "" +
	"\n" +
	"\x18mcp/v1/elicitation.proto\x12\x06mcp.v1\"\xc7\x01\n" +
	"\x0eMCPElicitation\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12.\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1a.mcp.v1.MCPElicitationModeR\x04mode\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12%\n" +
	"\x0eelicitation_id\x18\x05 \x01(\tR\relicitationId\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired*w\n" +
	"\x12MCPElicitationMode\x12$\n" +
	" MCP_ELICITATION_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MCP_ELICITATION_MODE_FORM\x10\x01\x12\x1c\n" +
	"\x18MCP_ELICITATION_MODE_URL\x10\x02BT\n" +
	"\n" +
	"com.mcp.v1B\x10ElicitationProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_elicitation_proto_rawDescOnce sync.Once
	file_mcp_v1_elicitation_proto_rawDescData []byte
)

func file_mcp_v1_elicitation_proto_rawDescGZIP() []byte {
	file_mcp_v1_elicitation_proto_rawDescOnce.Do(func() {
		file_mcp_v1_elicitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_elicitation_proto_rawDesc), len(file_mcp_v1_elicitation_proto_rawDesc)))
	})
	return file_mcp_v1_elicitation_proto_rawDescData
}

var file_mcp_v1_elicitation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_elicitation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_elicitation_proto_goTypes = []any{
	(MCPElicitationMode)(0), // 0: mcp.v1.MCPElicitationMode
	(*MCPElicitation)(nil),  // 1: mcp.v1.MCPElicitation
}
var file_mcp_v1_elicitation_proto_depIdxs = []int32{
	0, // 0: mcp.v1.MCPElicitation.mode:type_name -> mcp.v1.MCPElicitationMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_v1_elicitation_proto_init() }
func file_mcp_v1_elicitation_proto_init() {
	if File_mcp_v1_elicitation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_elicitation_proto_rawDesc), len(file_mcp_v1_elicitation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_elicitation_proto_goTypes,
		DependencyIndexes: file_mcp_v1_elicitation_proto_depIdxs,
		EnumInfos:         file_mcp_v1_elicitation_proto_enumTypes,
		MessageInfos:      file_mcp_v1_elicitation_proto_msgTypes,
	}.Build()
	File_mcp_v1_elicitation_proto = out.File
	file_mcp_v1_elicitation_proto_goTypes = nil
	file_mcp_v1_elicitation_proto_depIdxs = nil
}
