// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/elicitation.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPElicitation defines a confirmation dialog shown to the user before
// a tool executes. Used as: option (mcp.elicitation) = { ... };
//
// The form schema is a fully-qualified proto message name. The generator
// reads that message's fields, types, enums, comments, and field_behavior
// annotations to build a type-safe elicitation form.
//
// Example:
//
//	option (mcp.elicitation) = {
//	  message: "Please confirm before deleting."
//	  schema: "todo.v1.DeleteConfirmation"
//	};
type MCPElicitation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message shown to the user (e.g. "Are you sure you want to delete this?").
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Fully-qualified proto message name whose fields define the form schema.
	// Field types, descriptions, required-ness, and enum values are all
	// derived from the referenced message's proto definition.
	Schema        string `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPElicitation) Reset() {
	*x = MCPElicitation{}
	mi := &file_mcp_protobuf_elicitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPElicitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPElicitation) ProtoMessage() {}

func (x *MCPElicitation) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_elicitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPElicitation.ProtoReflect.Descriptor instead.
func (*MCPElicitation) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_elicitation_proto_rawDescGZIP(), []int{0}
}

func (x *MCPElicitation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MCPElicitation) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

var File_mcp_protobuf_elicitation_proto protoreflect.FileDescriptor

const file_mcp_protobuf_elicitation_proto_rawDesc = "" +
	"\n" +
	"\x1emcp/protobuf/elicitation.proto\x12\x03mcp\"B\n" +
	"\x0eMCPElicitation\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schemaBZ\n" +
	"\x10com.mcp.protobufB\x10ElicitationProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_elicitation_proto_rawDescOnce sync.Once
	file_mcp_protobuf_elicitation_proto_rawDescData []byte
)

func file_mcp_protobuf_elicitation_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_elicitation_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_elicitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_elicitation_proto_rawDesc), len(file_mcp_protobuf_elicitation_proto_rawDesc)))
	})
	return file_mcp_protobuf_elicitation_proto_rawDescData
}

var file_mcp_protobuf_elicitation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_protobuf_elicitation_proto_goTypes = []any{
	(*MCPElicitation)(nil), // 0: mcp.MCPElicitation
}
var file_mcp_protobuf_elicitation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_elicitation_proto_init() }
func file_mcp_protobuf_elicitation_proto_init() {
	if File_mcp_protobuf_elicitation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_elicitation_proto_rawDesc), len(file_mcp_protobuf_elicitation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_elicitation_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_elicitation_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_elicitation_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_elicitation_proto = out.File
	file_mcp_protobuf_elicitation_proto_goTypes = nil
	file_mcp_protobuf_elicitation_proto_depIdxs = nil
}
