// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/enum.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPEnumOptions attaches a description to an enum type.
// Used as: option (mcp.v1.enum) = { description: "..." };
// The description appears in the MCP tool inputSchema for enum fields.
type MCPEnumOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable description of the enum (e.g. for JSON Schema).
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPEnumOptions) Reset() {
	*x = MCPEnumOptions{}
	mi := &file_mcp_v1_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPEnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPEnumOptions) ProtoMessage() {}

func (x *MCPEnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPEnumOptions.ProtoReflect.Descriptor instead.
func (*MCPEnumOptions) Descriptor() ([]byte, []int) {
	return file_mcp_v1_enum_proto_rawDescGZIP(), []int{0}
}

func (x *MCPEnumOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// MCPEnumValueOptions attaches a description to an enum value.
// Used as: ENUM_VALUE = 0 [(mcp.v1.enum_value) = { description: "..." }];
// Value descriptions are combined into the schema description for the enum field.
type MCPEnumValueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable description of this enum value.
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPEnumValueOptions) Reset() {
	*x = MCPEnumValueOptions{}
	mi := &file_mcp_v1_enum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPEnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPEnumValueOptions) ProtoMessage() {}

func (x *MCPEnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_enum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPEnumValueOptions.ProtoReflect.Descriptor instead.
func (*MCPEnumValueOptions) Descriptor() ([]byte, []int) {
	return file_mcp_v1_enum_proto_rawDescGZIP(), []int{1}
}

func (x *MCPEnumValueOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_mcp_v1_enum_proto protoreflect.FileDescriptor

const file_mcp_v1_enum_proto_rawDesc = "" +
	"\n" +
	"\x11mcp/v1/enum.proto\x12\x06mcp.v1\"2\n" +
	"\x0eMCPEnumOptions\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"7\n" +
	"\x13MCPEnumValueOptions\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescriptionBM\n" +
	"\n" +
	"com.mcp.v1B\tEnumProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_enum_proto_rawDescOnce sync.Once
	file_mcp_v1_enum_proto_rawDescData []byte
)

func file_mcp_v1_enum_proto_rawDescGZIP() []byte {
	file_mcp_v1_enum_proto_rawDescOnce.Do(func() {
		file_mcp_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_enum_proto_rawDesc), len(file_mcp_v1_enum_proto_rawDesc)))
	})
	return file_mcp_v1_enum_proto_rawDescData
}

var file_mcp_v1_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcp_v1_enum_proto_goTypes = []any{
	(*MCPEnumOptions)(nil),      // 0: mcp.v1.MCPEnumOptions
	(*MCPEnumValueOptions)(nil), // 1: mcp.v1.MCPEnumValueOptions
}
var file_mcp_v1_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_v1_enum_proto_init() }
func file_mcp_v1_enum_proto_init() {
	if File_mcp_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_enum_proto_rawDesc), len(file_mcp_v1_enum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_enum_proto_goTypes,
		DependencyIndexes: file_mcp_v1_enum_proto_depIdxs,
		MessageInfos:      file_mcp_v1_enum_proto_msgTypes,
	}.Build()
	File_mcp_v1_enum_proto = out.File
	file_mcp_v1_enum_proto_goTypes = nil
	file_mcp_v1_enum_proto_depIdxs = nil
}
