// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/field_type.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPFieldType enumerates JSON Schema primitive types used by elicitation fields.
type MCPFieldType int32

const (
	// Default value; treated as string.
	MCPFieldType_MCP_FIELD_TYPE_UNSPECIFIED MCPFieldType = 0
	// JSON Schema "string" type.
	MCPFieldType_MCP_FIELD_TYPE_STRING MCPFieldType = 1
	// JSON Schema "number" type (floating-point).
	MCPFieldType_MCP_FIELD_TYPE_NUMBER MCPFieldType = 2
	// JSON Schema "boolean" type.
	MCPFieldType_MCP_FIELD_TYPE_BOOLEAN MCPFieldType = 3
	// JSON Schema "integer" type.
	MCPFieldType_MCP_FIELD_TYPE_INTEGER MCPFieldType = 4
)

// Enum value maps for MCPFieldType.
var (
	MCPFieldType_name = map[int32]string{
		0: "MCP_FIELD_TYPE_UNSPECIFIED",
		1: "MCP_FIELD_TYPE_STRING",
		2: "MCP_FIELD_TYPE_NUMBER",
		3: "MCP_FIELD_TYPE_BOOLEAN",
		4: "MCP_FIELD_TYPE_INTEGER",
	}
	MCPFieldType_value = map[string]int32{
		"MCP_FIELD_TYPE_UNSPECIFIED": 0,
		"MCP_FIELD_TYPE_STRING":      1,
		"MCP_FIELD_TYPE_NUMBER":      2,
		"MCP_FIELD_TYPE_BOOLEAN":     3,
		"MCP_FIELD_TYPE_INTEGER":     4,
	}
)

func (x MCPFieldType) Enum() *MCPFieldType {
	p := new(MCPFieldType)
	*p = x
	return p
}

func (x MCPFieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPFieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_field_type_proto_enumTypes[0].Descriptor()
}

func (MCPFieldType) Type() protoreflect.EnumType {
	return &file_mcp_v1_field_type_proto_enumTypes[0]
}

func (x MCPFieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPFieldType.Descriptor instead.
func (MCPFieldType) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_field_type_proto_rawDescGZIP(), []int{0}
}

var File_mcp_v1_field_type_proto protoreflect.FileDescriptor

const file_mcp_v1_field_type_proto_rawDesc = "" +
	"\n" +
	"\x17mcp/v1/field_type.proto\x12\x06mcp.v1*\x9c\x01\n" +
	"\fMCPFieldType\x12\x1e\n" +
	"\x1aMCP_FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MCP_FIELD_TYPE_STRING\x10\x01\x12\x19\n" +
	"\x15MCP_FIELD_TYPE_NUMBER\x10\x02\x12\x1a\n" +
	"\x16MCP_FIELD_TYPE_BOOLEAN\x10\x03\x12\x1a\n" +
	"\x16MCP_FIELD_TYPE_INTEGER\x10\x04BR\n" +
	"\n" +
	"com.mcp.v1B\x0eFieldTypeProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_field_type_proto_rawDescOnce sync.Once
	file_mcp_v1_field_type_proto_rawDescData []byte
)

func file_mcp_v1_field_type_proto_rawDescGZIP() []byte {
	file_mcp_v1_field_type_proto_rawDescOnce.Do(func() {
		file_mcp_v1_field_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_field_type_proto_rawDesc), len(file_mcp_v1_field_type_proto_rawDesc)))
	})
	return file_mcp_v1_field_type_proto_rawDescData
}

var file_mcp_v1_field_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_field_type_proto_goTypes = []any{
	(MCPFieldType)(0), // 0: mcp.v1.MCPFieldType
}
var file_mcp_v1_field_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_v1_field_type_proto_init() }
func file_mcp_v1_field_type_proto_init() {
	if File_mcp_v1_field_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_field_type_proto_rawDesc), len(file_mcp_v1_field_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_field_type_proto_goTypes,
		DependencyIndexes: file_mcp_v1_field_type_proto_depIdxs,
		EnumInfos:         file_mcp_v1_field_type_proto_enumTypes,
	}.Build()
	File_mcp_v1_field_type_proto = out.File
	file_mcp_v1_field_type_proto_goTypes = nil
	file_mcp_v1_field_type_proto_depIdxs = nil
}
