// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/field.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPFieldFormat specifies the JSON Schema format keyword value for a field.
// Only the subset of formats with broadly consistent client support is listed.
type MCPFieldFormat int32

const (
	// No explicit format. The format keyword is omitted from the generated
	// schema, leaving it to be inferred from the proto field type.
	MCPFieldFormat_MCP_FIELD_FORMAT_UNSPECIFIED MCPFieldFormat = 0
	// ISO 8601 date-time string, e.g. "2025-01-12T15:00:58Z".
	MCPFieldFormat_MCP_FIELD_FORMAT_DATE_TIME MCPFieldFormat = 1
	// ISO 8601 date string, e.g. "2025-01-12".
	MCPFieldFormat_MCP_FIELD_FORMAT_DATE MCPFieldFormat = 2
	// ISO 8601 time string, e.g. "15:00:58Z".
	MCPFieldFormat_MCP_FIELD_FORMAT_TIME MCPFieldFormat = 3
	// An absolute URI, e.g. "https://example.com/resource".
	MCPFieldFormat_MCP_FIELD_FORMAT_URI MCPFieldFormat = 4
	// A UUID string, e.g. "550e8400-e29b-41d4-a716-446655440000".
	MCPFieldFormat_MCP_FIELD_FORMAT_UUID MCPFieldFormat = 5
	// An email address, e.g. "user@example.com".
	MCPFieldFormat_MCP_FIELD_FORMAT_EMAIL MCPFieldFormat = 6
	// A base64-encoded byte string.
	MCPFieldFormat_MCP_FIELD_FORMAT_BYTE MCPFieldFormat = 7
)

// Enum value maps for MCPFieldFormat.
var (
	MCPFieldFormat_name = map[int32]string{
		0: "MCP_FIELD_FORMAT_UNSPECIFIED",
		1: "MCP_FIELD_FORMAT_DATE_TIME",
		2: "MCP_FIELD_FORMAT_DATE",
		3: "MCP_FIELD_FORMAT_TIME",
		4: "MCP_FIELD_FORMAT_URI",
		5: "MCP_FIELD_FORMAT_UUID",
		6: "MCP_FIELD_FORMAT_EMAIL",
		7: "MCP_FIELD_FORMAT_BYTE",
	}
	MCPFieldFormat_value = map[string]int32{
		"MCP_FIELD_FORMAT_UNSPECIFIED": 0,
		"MCP_FIELD_FORMAT_DATE_TIME":   1,
		"MCP_FIELD_FORMAT_DATE":        2,
		"MCP_FIELD_FORMAT_TIME":        3,
		"MCP_FIELD_FORMAT_URI":         4,
		"MCP_FIELD_FORMAT_UUID":        5,
		"MCP_FIELD_FORMAT_EMAIL":       6,
		"MCP_FIELD_FORMAT_BYTE":        7,
	}
)

func (x MCPFieldFormat) Enum() *MCPFieldFormat {
	p := new(MCPFieldFormat)
	*p = x
	return p
}

func (x MCPFieldFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPFieldFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_field_proto_enumTypes[0].Descriptor()
}

func (MCPFieldFormat) Type() protoreflect.EnumType {
	return &file_mcp_v1_field_proto_enumTypes[0]
}

func (x MCPFieldFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPFieldFormat.Descriptor instead.
func (MCPFieldFormat) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_field_proto_rawDescGZIP(), []int{0}
}

// MCPFieldOptions annotates a proto field with MCP-specific metadata used
// during JSON Schema generation and MCP tool registration.
type MCPFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable description of the field shown in the MCP tool's input schema.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Example values for this field, shown to the LLM as schema examples.
	Examples []string `protobuf:"bytes,2,rep,name=examples,proto3" json:"examples,omitempty"`
	// When true, signals to clients that this field is deprecated and may be
	// removed in a future version.
	Deprecated bool `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// JSON Schema format keyword to apply to this field. Overrides the format
	// inferred from the proto field type (e.g. bytes fields default to "byte").
	// Set to MCP_FIELD_FORMAT_UNSPECIFIED to suppress the format keyword.
	Format MCPFieldFormat `protobuf:"varint,4,opt,name=format,proto3,enum=mcp.v1.MCPFieldFormat" json:"format,omitempty"`
	// JSON Schema type to apply to this field. Overrides the type inferred from
	// the proto field type. Useful for fields whose wire type does not match their
	// intended schema type (e.g. an int64 that should appear as "string" in JSON).
	Type MCPFieldType `protobuf:"varint,5,opt,name=type,proto3,enum=mcp.v1.MCPFieldType" json:"type,omitempty"`
	// Display name for the field, preferred over its proto name in UI and
	// end-user contexts. Carried onto a prompt argument's title when this field
	// belongs to a prompt's schema message.
	Title         *string `protobuf:"bytes,6,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPFieldOptions) Reset() {
	*x = MCPFieldOptions{}
	mi := &file_mcp_v1_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPFieldOptions) ProtoMessage() {}

func (x *MCPFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPFieldOptions.ProtoReflect.Descriptor instead.
func (*MCPFieldOptions) Descriptor() ([]byte, []int) {
	return file_mcp_v1_field_proto_rawDescGZIP(), []int{0}
}

func (x *MCPFieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPFieldOptions) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *MCPFieldOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *MCPFieldOptions) GetFormat() MCPFieldFormat {
	if x != nil {
		return x.Format
	}
	return MCPFieldFormat_MCP_FIELD_FORMAT_UNSPECIFIED
}

func (x *MCPFieldOptions) GetType() MCPFieldType {
	if x != nil {
		return x.Type
	}
	return MCPFieldType_MCP_FIELD_TYPE_UNSPECIFIED
}

func (x *MCPFieldOptions) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

var File_mcp_v1_field_proto protoreflect.FileDescriptor

const file_mcp_v1_field_proto_rawDesc = "" +
	"\n" +
	"\x12mcp/v1/field.proto\x12\x06mcp.v1\x1a\x17mcp/v1/field_type.proto\"\xee\x01\n" +
	"\x0fMCPFieldOptions\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x02 \x03(\tR\bexamples\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\bR\n" +
	"deprecated\x12.\n" +
	"\x06format\x18\x04 \x01(\x0e2\x16.mcp.v1.MCPFieldFormatR\x06format\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.mcp.v1.MCPFieldTypeR\x04type\x12\x19\n" +
	"\x05title\x18\x06 \x01(\tH\x00R\x05title\x88\x01\x01B\b\n" +
	"\x06_title*\xf4\x01\n" +
	"\x0eMCPFieldFormat\x12 \n" +
	"\x1cMCP_FIELD_FORMAT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMCP_FIELD_FORMAT_DATE_TIME\x10\x01\x12\x19\n" +
	"\x15MCP_FIELD_FORMAT_DATE\x10\x02\x12\x19\n" +
	"\x15MCP_FIELD_FORMAT_TIME\x10\x03\x12\x18\n" +
	"\x14MCP_FIELD_FORMAT_URI\x10\x04\x12\x19\n" +
	"\x15MCP_FIELD_FORMAT_UUID\x10\x05\x12\x1a\n" +
	"\x16MCP_FIELD_FORMAT_EMAIL\x10\x06\x12\x19\n" +
	"\x15MCP_FIELD_FORMAT_BYTE\x10\aBN\n" +
	"\n" +
	"com.mcp.v1B\n" +
	"FieldProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_field_proto_rawDescOnce sync.Once
	file_mcp_v1_field_proto_rawDescData []byte
)

func file_mcp_v1_field_proto_rawDescGZIP() []byte {
	file_mcp_v1_field_proto_rawDescOnce.Do(func() {
		file_mcp_v1_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_field_proto_rawDesc), len(file_mcp_v1_field_proto_rawDesc)))
	})
	return file_mcp_v1_field_proto_rawDescData
}

var file_mcp_v1_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_field_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_field_proto_goTypes = []any{
	(MCPFieldFormat)(0),     // 0: mcp.v1.MCPFieldFormat
	(*MCPFieldOptions)(nil), // 1: mcp.v1.MCPFieldOptions
	(MCPFieldType)(0),       // 2: mcp.v1.MCPFieldType
}
var file_mcp_v1_field_proto_depIdxs = []int32{
	0, // 0: mcp.v1.MCPFieldOptions.format:type_name -> mcp.v1.MCPFieldFormat
	2, // 1: mcp.v1.MCPFieldOptions.type:type_name -> mcp.v1.MCPFieldType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_v1_field_proto_init() }
func file_mcp_v1_field_proto_init() {
	if File_mcp_v1_field_proto != nil {
		return
	}
	file_mcp_v1_field_type_proto_init()
	file_mcp_v1_field_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_field_proto_rawDesc), len(file_mcp_v1_field_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_field_proto_goTypes,
		DependencyIndexes: file_mcp_v1_field_proto_depIdxs,
		EnumInfos:         file_mcp_v1_field_proto_enumTypes,
		MessageInfos:      file_mcp_v1_field_proto_msgTypes,
	}.Build()
	File_mcp_v1_field_proto = out.File
	file_mcp_v1_field_proto_goTypes = nil
	file_mcp_v1_field_proto_depIdxs = nil
}
