// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/field.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPFieldOptions attaches JSON Schema metadata to a message field.
// Used as: option (mcp.field) = { description: "...", examples: [...], ... };
// These appear in the MCP tool inputSchema for that field.
type MCPFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable description of the field (e.g. for JSON Schema).
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Example values to guide LLMs (JSON Schema "examples").
	Examples []string `protobuf:"bytes,2,rep,name=examples,proto3" json:"examples,omitempty"`
	// If true, marks the field as deprecated in the schema.
	Deprecated bool `protobuf:"varint,3,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// JSON Schema format override (e.g. "uri", "email", "uuid").
	// When set, overrides auto-detected format (e.g. from buf.validate).
	Format        string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPFieldOptions) Reset() {
	*x = MCPFieldOptions{}
	mi := &file_mcp_protobuf_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPFieldOptions) ProtoMessage() {}

func (x *MCPFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPFieldOptions.ProtoReflect.Descriptor instead.
func (*MCPFieldOptions) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_field_proto_rawDescGZIP(), []int{0}
}

func (x *MCPFieldOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPFieldOptions) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *MCPFieldOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *MCPFieldOptions) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_mcp_protobuf_field_proto protoreflect.FileDescriptor

const file_mcp_protobuf_field_proto_rawDesc = "" +
	"\n" +
	"\x18mcp/protobuf/field.proto\x12\x03mcp\"\x87\x01\n" +
	"\x0fMCPFieldOptions\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x02 \x03(\tR\bexamples\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x03 \x01(\bR\n" +
	"deprecated\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06formatBT\n" +
	"\x10com.mcp.protobufB\n" +
	"FieldProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_field_proto_rawDescOnce sync.Once
	file_mcp_protobuf_field_proto_rawDescData []byte
)

func file_mcp_protobuf_field_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_field_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_field_proto_rawDesc), len(file_mcp_protobuf_field_proto_rawDesc)))
	})
	return file_mcp_protobuf_field_proto_rawDescData
}

var file_mcp_protobuf_field_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_protobuf_field_proto_goTypes = []any{
	(*MCPFieldOptions)(nil), // 0: mcp.MCPFieldOptions
}
var file_mcp_protobuf_field_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_field_proto_init() }
func file_mcp_protobuf_field_proto_init() {
	if File_mcp_protobuf_field_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_field_proto_rawDesc), len(file_mcp_protobuf_field_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_field_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_field_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_field_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_field_proto = out.File
	file_mcp_protobuf_field_proto_goTypes = nil
	file_mcp_protobuf_field_proto_depIdxs = nil
}
