// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/icon.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPIconTheme indicates the background context an icon is designed for.
type MCPIconTheme int32

const (
	// No theme specified. The icon is suitable for any background.
	MCPIconTheme_MCP_ICON_THEME_UNSPECIFIED MCPIconTheme = 0
	// The icon is designed for display on a light background.
	MCPIconTheme_MCP_ICON_THEME_LIGHT MCPIconTheme = 1
	// The icon is designed for display on a dark background.
	MCPIconTheme_MCP_ICON_THEME_DARK MCPIconTheme = 2
)

// Enum value maps for MCPIconTheme.
var (
	MCPIconTheme_name = map[int32]string{
		0: "MCP_ICON_THEME_UNSPECIFIED",
		1: "MCP_ICON_THEME_LIGHT",
		2: "MCP_ICON_THEME_DARK",
	}
	MCPIconTheme_value = map[string]int32{
		"MCP_ICON_THEME_UNSPECIFIED": 0,
		"MCP_ICON_THEME_LIGHT":       1,
		"MCP_ICON_THEME_DARK":        2,
	}
)

func (x MCPIconTheme) Enum() *MCPIconTheme {
	p := new(MCPIconTheme)
	*p = x
	return p
}

func (x MCPIconTheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPIconTheme) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_icon_proto_enumTypes[0].Descriptor()
}

func (MCPIconTheme) Type() protoreflect.EnumType {
	return &file_mcp_v1_icon_proto_enumTypes[0]
}

func (x MCPIconTheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPIconTheme.Descriptor instead.
func (MCPIconTheme) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_icon_proto_rawDescGZIP(), []int{0}
}

// MCPIcon describes a single icon image associated with an MCP primitive.
// It corresponds to the Icon struct in the MCP SDKs.
//
// Icons live in their own file because tools, prompts, resources and the app
// all carry them, and resource.proto already imports prompt.proto — keeping
// them beside resources would make that import cycle.
type MCPIcon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI pointing to the icon resource. This can be an HTTP/HTTPS URL pointing
	// to an image file, or an inline `data:` URI carrying the image bytes.
	// Required.
	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	// MIME type of the icon image. Should be provided when the server's
	// Content-Type header is missing or too generic.
	MimeType *string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	// Size specification for the icon. Examples:
	//
	//	["48x48"]           — single fixed size
	//	["any"]             — scalable format such as SVG
	//	["48x48", "96x96"]  — multiple available sizes
	Sizes []string `protobuf:"bytes,3,rep,name=sizes,proto3" json:"sizes,omitempty"`
	// The background context this icon is designed for.
	// Omit if the icon is suitable for any background.
	Theme         MCPIconTheme `protobuf:"varint,4,opt,name=theme,proto3,enum=mcp.v1.MCPIconTheme" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPIcon) Reset() {
	*x = MCPIcon{}
	mi := &file_mcp_v1_icon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPIcon) ProtoMessage() {}

func (x *MCPIcon) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_icon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPIcon.ProtoReflect.Descriptor instead.
func (*MCPIcon) Descriptor() ([]byte, []int) {
	return file_mcp_v1_icon_proto_rawDescGZIP(), []int{0}
}

func (x *MCPIcon) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MCPIcon) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *MCPIcon) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *MCPIcon) GetTheme() MCPIconTheme {
	if x != nil {
		return x.Theme
	}
	return MCPIconTheme_MCP_ICON_THEME_UNSPECIFIED
}

var File_mcp_v1_icon_proto protoreflect.FileDescriptor

const file_mcp_v1_icon_proto_rawDesc = "" +
	"\n" +
	"\x11mcp/v1/icon.proto\x12\x06mcp.v1\"\x8d\x01\n" +
	"\aMCPIcon\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12 \n" +
	"\tmime_type\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x14\n" +
	"\x05sizes\x18\x03 \x03(\tR\x05sizes\x12*\n" +
	"\x05theme\x18\x04 \x01(\x0e2\x14.mcp.v1.MCPIconThemeR\x05themeB\f\n" +
	"\n" +
	"_mime_type*a\n" +
	"\fMCPIconTheme\x12\x1e\n" +
	"\x1aMCP_ICON_THEME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MCP_ICON_THEME_LIGHT\x10\x01\x12\x17\n" +
	"\x13MCP_ICON_THEME_DARK\x10\x02BM\n" +
	"\n" +
	"com.mcp.v1B\tIconProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_icon_proto_rawDescOnce sync.Once
	file_mcp_v1_icon_proto_rawDescData []byte
)

func file_mcp_v1_icon_proto_rawDescGZIP() []byte {
	file_mcp_v1_icon_proto_rawDescOnce.Do(func() {
		file_mcp_v1_icon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_icon_proto_rawDesc), len(file_mcp_v1_icon_proto_rawDesc)))
	})
	return file_mcp_v1_icon_proto_rawDescData
}

var file_mcp_v1_icon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_icon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_v1_icon_proto_goTypes = []any{
	(MCPIconTheme)(0), // 0: mcp.v1.MCPIconTheme
	(*MCPIcon)(nil),   // 1: mcp.v1.MCPIcon
}
var file_mcp_v1_icon_proto_depIdxs = []int32{
	0, // 0: mcp.v1.MCPIcon.theme:type_name -> mcp.v1.MCPIconTheme
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_v1_icon_proto_init() }
func file_mcp_v1_icon_proto_init() {
	if File_mcp_v1_icon_proto != nil {
		return
	}
	file_mcp_v1_icon_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_icon_proto_rawDesc), len(file_mcp_v1_icon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_icon_proto_goTypes,
		DependencyIndexes: file_mcp_v1_icon_proto_depIdxs,
		EnumInfos:         file_mcp_v1_icon_proto_enumTypes,
		MessageInfos:      file_mcp_v1_icon_proto_msgTypes,
	}.Build()
	File_mcp_v1_icon_proto = out.File
	file_mcp_v1_icon_proto_goTypes = nil
	file_mcp_v1_icon_proto_depIdxs = nil
}
