// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/mime_type.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPMimeType enumerates common MIME types for MCP resources.
type MCPMimeType int32

const (
	// Default; treated as application/json.
	MCPMimeType_MCP_MIME_TYPE_UNSPECIFIED MCPMimeType = 0
	// application/json
	MCPMimeType_MCP_MIME_TYPE_APPLICATION_JSON MCPMimeType = 1
	// text/plain
	MCPMimeType_MCP_MIME_TYPE_TEXT_PLAIN MCPMimeType = 2
	// text/html
	MCPMimeType_MCP_MIME_TYPE_TEXT_HTML MCPMimeType = 3
	// text/markdown
	MCPMimeType_MCP_MIME_TYPE_TEXT_MARKDOWN MCPMimeType = 4
	// application/xml
	MCPMimeType_MCP_MIME_TYPE_APPLICATION_XML MCPMimeType = 5
	// application/octet-stream
	MCPMimeType_MCP_MIME_TYPE_APPLICATION_OCTET_STREAM MCPMimeType = 6
	// application/pdf
	MCPMimeType_MCP_MIME_TYPE_APPLICATION_PDF MCPMimeType = 7
	// image/png
	MCPMimeType_MCP_MIME_TYPE_IMAGE_PNG MCPMimeType = 8
	// image/jpeg
	MCPMimeType_MCP_MIME_TYPE_IMAGE_JPEG MCPMimeType = 9
)

// Enum value maps for MCPMimeType.
var (
	MCPMimeType_name = map[int32]string{
		0: "MCP_MIME_TYPE_UNSPECIFIED",
		1: "MCP_MIME_TYPE_APPLICATION_JSON",
		2: "MCP_MIME_TYPE_TEXT_PLAIN",
		3: "MCP_MIME_TYPE_TEXT_HTML",
		4: "MCP_MIME_TYPE_TEXT_MARKDOWN",
		5: "MCP_MIME_TYPE_APPLICATION_XML",
		6: "MCP_MIME_TYPE_APPLICATION_OCTET_STREAM",
		7: "MCP_MIME_TYPE_APPLICATION_PDF",
		8: "MCP_MIME_TYPE_IMAGE_PNG",
		9: "MCP_MIME_TYPE_IMAGE_JPEG",
	}
	MCPMimeType_value = map[string]int32{
		"MCP_MIME_TYPE_UNSPECIFIED":              0,
		"MCP_MIME_TYPE_APPLICATION_JSON":         1,
		"MCP_MIME_TYPE_TEXT_PLAIN":               2,
		"MCP_MIME_TYPE_TEXT_HTML":                3,
		"MCP_MIME_TYPE_TEXT_MARKDOWN":            4,
		"MCP_MIME_TYPE_APPLICATION_XML":          5,
		"MCP_MIME_TYPE_APPLICATION_OCTET_STREAM": 6,
		"MCP_MIME_TYPE_APPLICATION_PDF":          7,
		"MCP_MIME_TYPE_IMAGE_PNG":                8,
		"MCP_MIME_TYPE_IMAGE_JPEG":               9,
	}
)

func (x MCPMimeType) Enum() *MCPMimeType {
	p := new(MCPMimeType)
	*p = x
	return p
}

func (x MCPMimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPMimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_protobuf_mime_type_proto_enumTypes[0].Descriptor()
}

func (MCPMimeType) Type() protoreflect.EnumType {
	return &file_mcp_protobuf_mime_type_proto_enumTypes[0]
}

func (x MCPMimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPMimeType.Descriptor instead.
func (MCPMimeType) EnumDescriptor() ([]byte, []int) {
	return file_mcp_protobuf_mime_type_proto_rawDescGZIP(), []int{0}
}

var File_mcp_protobuf_mime_type_proto protoreflect.FileDescriptor

const file_mcp_protobuf_mime_type_proto_rawDesc = "" +
	"\n" +
	"\x1cmcp/protobuf/mime_type.proto\x12\x03mcp*\xd9\x02\n" +
	"\vMCPMimeType\x12\x1d\n" +
	"\x19MCP_MIME_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMCP_MIME_TYPE_APPLICATION_JSON\x10\x01\x12\x1c\n" +
	"\x18MCP_MIME_TYPE_TEXT_PLAIN\x10\x02\x12\x1b\n" +
	"\x17MCP_MIME_TYPE_TEXT_HTML\x10\x03\x12\x1f\n" +
	"\x1bMCP_MIME_TYPE_TEXT_MARKDOWN\x10\x04\x12!\n" +
	"\x1dMCP_MIME_TYPE_APPLICATION_XML\x10\x05\x12*\n" +
	"&MCP_MIME_TYPE_APPLICATION_OCTET_STREAM\x10\x06\x12!\n" +
	"\x1dMCP_MIME_TYPE_APPLICATION_PDF\x10\a\x12\x1b\n" +
	"\x17MCP_MIME_TYPE_IMAGE_PNG\x10\b\x12\x1c\n" +
	"\x18MCP_MIME_TYPE_IMAGE_JPEG\x10\tBW\n" +
	"\x10com.mcp.protobufB\rMimeTypeProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_mime_type_proto_rawDescOnce sync.Once
	file_mcp_protobuf_mime_type_proto_rawDescData []byte
)

func file_mcp_protobuf_mime_type_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_mime_type_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_mime_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_mime_type_proto_rawDesc), len(file_mcp_protobuf_mime_type_proto_rawDesc)))
	})
	return file_mcp_protobuf_mime_type_proto_rawDescData
}

var file_mcp_protobuf_mime_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_protobuf_mime_type_proto_goTypes = []any{
	(MCPMimeType)(0), // 0: mcp.MCPMimeType
}
var file_mcp_protobuf_mime_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_mime_type_proto_init() }
func file_mcp_protobuf_mime_type_proto_init() {
	if File_mcp_protobuf_mime_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_mime_type_proto_rawDesc), len(file_mcp_protobuf_mime_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_mime_type_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_mime_type_proto_depIdxs,
		EnumInfos:         file_mcp_protobuf_mime_type_proto_enumTypes,
	}.Build()
	File_mcp_protobuf_mime_type_proto = out.File
	file_mcp_protobuf_mime_type_proto_goTypes = nil
	file_mcp_protobuf_mime_type_proto_depIdxs = nil
}
