// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/progress.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPProgress is sent in server-streaming RPC chunks to report progress to MCP clients.
// Use in a oneof with your result type:
//
//	message CreateTodoStreamChunk {
//	  oneof payload {
//	    mcp.v1.MCPProgress progress = 1;
//	    Todo result = 2;
//	  }
//	}
//	rpc CreateTodo(CreateTodoRequest) returns (stream CreateTodoStreamChunk) {
//	  option (mcp.v1.tool) = { progress: true };
//	}
//
// How to send _meta (MCP client):
//
// When calling a tool, include progressToken in params._meta. The progressToken
// can be a string or integer; it correlates progress notifications with the request.
//
//	{
//	  "method": "tools/call",
//	  "params": {
//	    "name": "counter_service-count_v1",
//	    "arguments": { "to": 5 },
//	    "_meta": { "progressToken": "abc123" }
//	  }
//	}
//
// The gateway forwards progressToken via gRPC metadata (key: mcp-progress-token).
// gRPC servers can check metadata to only send MCPProgress chunks when requested.
//
// The plugin auto-generates MCP tool handlers that send progress notifications
// and return the final result.
type MCPProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Extra metadata associated with the progress update.
	Meta map[string]*structpb.Struct `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Token identifying the progress stream, echoed back from the client's
	// params._meta.progressToken. The MCP spec allows the client to send either
	// a string or an integer, so exactly one of these is set.
	//
	// Types that are valid to be assigned to ProgressToken:
	//
	//	*MCPProgress_TokenString
	//	*MCPProgress_TokenInt
	ProgressToken isMCPProgress_ProgressToken `protobuf_oneof:"progress_token"`
	// Human-readable status text.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Current progress amount.
	Progress float64 `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`
	// Expected total amount.
	Total         *float64 `protobuf:"fixed64,5,opt,name=total,proto3,oneof" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPProgress) Reset() {
	*x = MCPProgress{}
	mi := &file_mcp_v1_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPProgress) ProtoMessage() {}

func (x *MCPProgress) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPProgress.ProtoReflect.Descriptor instead.
func (*MCPProgress) Descriptor() ([]byte, []int) {
	return file_mcp_v1_progress_proto_rawDescGZIP(), []int{0}
}

func (x *MCPProgress) GetMeta() map[string]*structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MCPProgress) GetProgressToken() isMCPProgress_ProgressToken {
	if x != nil {
		return x.ProgressToken
	}
	return nil
}

func (x *MCPProgress) GetTokenString() string {
	if x != nil {
		if x, ok := x.ProgressToken.(*MCPProgress_TokenString); ok {
			return x.TokenString
		}
	}
	return ""
}

func (x *MCPProgress) GetTokenInt() int64 {
	if x != nil {
		if x, ok := x.ProgressToken.(*MCPProgress_TokenInt); ok {
			return x.TokenInt
		}
	}
	return 0
}

func (x *MCPProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MCPProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *MCPProgress) GetTotal() float64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type isMCPProgress_ProgressToken interface {
	isMCPProgress_ProgressToken()
}

type MCPProgress_TokenString struct {
	// Token the client sent as a JSON string, e.g. "abc123".
	TokenString string `protobuf:"bytes,2,opt,name=token_string,json=tokenString,proto3,oneof"`
}

type MCPProgress_TokenInt struct {
	// Token the client sent as a JSON integer, e.g. 42.
	TokenInt int64 `protobuf:"varint,6,opt,name=token_int,json=tokenInt,proto3,oneof"`
}

func (*MCPProgress_TokenString) isMCPProgress_ProgressToken() {}

func (*MCPProgress_TokenInt) isMCPProgress_ProgressToken() {}

var File_mcp_v1_progress_proto protoreflect.FileDescriptor

const file_mcp_v1_progress_proto_rawDesc = "" +
	"\n" +
	"\x15mcp/v1/progress.proto\x12\x06mcp.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xc3\x02\n" +
	"\vMCPProgress\x121\n" +
	"\x04meta\x18\x01 \x03(\v2\x1d.mcp.v1.MCPProgress.MetaEntryR\x04meta\x12#\n" +
	"\ftoken_string\x18\x02 \x01(\tH\x00R\vtokenString\x12\x1d\n" +
	"\ttoken_int\x18\x06 \x01(\x03H\x00R\btokenInt\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\x12\x19\n" +
	"\x05total\x18\x05 \x01(\x01H\x01R\x05total\x88\x01\x01\x1aP\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01B\x10\n" +
	"\x0eprogress_tokenB\b\n" +
	"\x06_totalBQ\n" +
	"\n" +
	"com.mcp.v1B\rProgressProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_progress_proto_rawDescOnce sync.Once
	file_mcp_v1_progress_proto_rawDescData []byte
)

func file_mcp_v1_progress_proto_rawDescGZIP() []byte {
	file_mcp_v1_progress_proto_rawDescOnce.Do(func() {
		file_mcp_v1_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_progress_proto_rawDesc), len(file_mcp_v1_progress_proto_rawDesc)))
	})
	return file_mcp_v1_progress_proto_rawDescData
}

var file_mcp_v1_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcp_v1_progress_proto_goTypes = []any{
	(*MCPProgress)(nil),     // 0: mcp.v1.MCPProgress
	nil,                     // 1: mcp.v1.MCPProgress.MetaEntry
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_mcp_v1_progress_proto_depIdxs = []int32{
	1, // 0: mcp.v1.MCPProgress.meta:type_name -> mcp.v1.MCPProgress.MetaEntry
	2, // 1: mcp.v1.MCPProgress.MetaEntry.value:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_v1_progress_proto_init() }
func file_mcp_v1_progress_proto_init() {
	if File_mcp_v1_progress_proto != nil {
		return
	}
	file_mcp_v1_progress_proto_msgTypes[0].OneofWrappers = []any{
		(*MCPProgress_TokenString)(nil),
		(*MCPProgress_TokenInt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_progress_proto_rawDesc), len(file_mcp_v1_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_progress_proto_goTypes,
		DependencyIndexes: file_mcp_v1_progress_proto_depIdxs,
		MessageInfos:      file_mcp_v1_progress_proto_msgTypes,
	}.Build()
	File_mcp_v1_progress_proto = out.File
	file_mcp_v1_progress_proto_goTypes = nil
	file_mcp_v1_progress_proto_depIdxs = nil
}
