// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/progress.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPProgress is sent in server-streaming RPC chunks to report progress to MCP clients.
// Use in a oneof with your result type:
//
//	message CreateTodoStreamChunk {
//	  oneof payload {
//	    mcp.MCPProgress progress = 1;
//	    Todo result = 2;
//	  }
//	}
//	rpc CreateTodo(CreateTodoRequest) returns (stream CreateTodoStreamChunk) {
//	  option (mcp.tool) = { progress: true };
//	}
//
// How to send _meta (MCP client):
//
// When calling a tool, include progressToken in params._meta. The progressToken
// can be a string or integer; it correlates progress notifications with the request.
//
//	{
//	  "method": "tools/call",
//	  "params": {
//	    "name": "counter_service-count_v1",
//	    "arguments": { "to": 5 },
//	    "_meta": { "progressToken": "abc123" }
//	  }
//	}
//
// The gateway forwards progressToken via gRPC metadata (key: mcp-progress-token).
// gRPC servers can check metadata to only send MCPProgress chunks when requested.
//
// The plugin auto-generates MCP tool handlers that send progress notifications
// and return the final result.
type MCPProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Progress value so far (must increase with each chunk).
	Progress float64 `protobuf:"fixed64,1,opt,name=progress,proto3" json:"progress,omitempty"`
	// Optional total; omit if unknown.
	Total *float64 `protobuf:"fixed64,2,opt,name=total,proto3,oneof" json:"total,omitempty"`
	// Human-readable status message.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPProgress) Reset() {
	*x = MCPProgress{}
	mi := &file_mcp_protobuf_progress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPProgress) ProtoMessage() {}

func (x *MCPProgress) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_progress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPProgress.ProtoReflect.Descriptor instead.
func (*MCPProgress) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_progress_proto_rawDescGZIP(), []int{0}
}

func (x *MCPProgress) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *MCPProgress) GetTotal() float64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

func (x *MCPProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mcp_protobuf_progress_proto protoreflect.FileDescriptor

const file_mcp_protobuf_progress_proto_rawDesc = "" +
	"\n" +
	"\x1bmcp/protobuf/progress.proto\x12\x03mcp\"h\n" +
	"\vMCPProgress\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x01R\bprogress\x12\x19\n" +
	"\x05total\x18\x02 \x01(\x01H\x00R\x05total\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\b\n" +
	"\x06_totalBW\n" +
	"\x10com.mcp.protobufB\rProgressProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_progress_proto_rawDescOnce sync.Once
	file_mcp_protobuf_progress_proto_rawDescData []byte
)

func file_mcp_protobuf_progress_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_progress_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_progress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_progress_proto_rawDesc), len(file_mcp_protobuf_progress_proto_rawDesc)))
	})
	return file_mcp_protobuf_progress_proto_rawDescData
}

var file_mcp_protobuf_progress_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_protobuf_progress_proto_goTypes = []any{
	(*MCPProgress)(nil), // 0: mcp.MCPProgress
}
var file_mcp_protobuf_progress_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_progress_proto_init() }
func file_mcp_protobuf_progress_proto_init() {
	if File_mcp_protobuf_progress_proto != nil {
		return
	}
	file_mcp_protobuf_progress_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_progress_proto_rawDesc), len(file_mcp_protobuf_progress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_progress_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_progress_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_progress_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_progress_proto = out.File
	file_mcp_protobuf_progress_proto_goTypes = nil
	file_mcp_protobuf_progress_proto_depIdxs = nil
}
