// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/prompt.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPRole specifies the intended recipient of a prompt message.
type MCPRole int32

const (
	// No role specified. Treated as MCP_ROLE_USER.
	MCPRole_MCP_ROLE_UNSPECIFIED MCPRole = 0
	// The user role; default when omitted.
	MCPRole_MCP_ROLE_USER MCPRole = 1
	// The assistant role (e.g. for Claude).
	MCPRole_MCP_ROLE_ASSISTANT MCPRole = 2
)

// Enum value maps for MCPRole.
var (
	MCPRole_name = map[int32]string{
		0: "MCP_ROLE_UNSPECIFIED",
		1: "MCP_ROLE_USER",
		2: "MCP_ROLE_ASSISTANT",
	}
	MCPRole_value = map[string]int32{
		"MCP_ROLE_UNSPECIFIED": 0,
		"MCP_ROLE_USER":        1,
		"MCP_ROLE_ASSISTANT":   2,
	}
)

func (x MCPRole) Enum() *MCPRole {
	p := new(MCPRole)
	*p = x
	return p
}

func (x MCPRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPRole) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_prompt_proto_enumTypes[0].Descriptor()
}

func (MCPRole) Type() protoreflect.EnumType {
	return &file_mcp_v1_prompt_proto_enumTypes[0]
}

func (x MCPRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPRole.Descriptor instead.
func (MCPRole) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_prompt_proto_rawDescGZIP(), []int{0}
}

// MCPPrompt defines a reusable prompt template exposed at the service level.
//
// The arguments are defined as a proper proto message referenced by schema.
// Field types, descriptions, required-ness, and enum values are all
// derived from the referenced message's proto definition.
//
// Example:
//
//	prompts: [
//	  {
//	    name: "summarize_todos"
//	    description: "Summarize all pending todo items for a user"
//	    schema: "todo.v1.SummarizeTodosArgs"
//	  }
//	]
type MCPPrompt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique prompt identifier (e.g. "summarize_todos"). Only set when overriding.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Human-readable description of what this prompt does. Only set when overriding.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Fully-qualified proto message name whose fields define the prompt arguments.
	Schema string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// Role of the generated prompt message; defaults to user.
	Role          MCPRole `protobuf:"varint,4,opt,name=role,proto3,enum=mcp.v1.MCPRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPPrompt) Reset() {
	*x = MCPPrompt{}
	mi := &file_mcp_v1_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPPrompt) ProtoMessage() {}

func (x *MCPPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPPrompt.ProtoReflect.Descriptor instead.
func (*MCPPrompt) Descriptor() ([]byte, []int) {
	return file_mcp_v1_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *MCPPrompt) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *MCPPrompt) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MCPPrompt) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *MCPPrompt) GetRole() MCPRole {
	if x != nil {
		return x.Role
	}
	return MCPRole_MCP_ROLE_UNSPECIFIED
}

// MCPToolOptions configures an individual RPC method as an MCP tool.
// Used as: option (mcp.v1.tool) = { ... };
type MCPToolOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override the auto-generated MCP tool identifier. Only set when overriding.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Override the tool description (defaults to the RPC's leading comment). Only set when overriding.
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// When true, this RPC supports MCP progress notifications. Clients may include
	// progressToken in params._meta; the server will send progress updates during
	// execution. Requires a server-streaming RPC whose response has a oneof with
	// mcp.v1.MCPProgress and the result type.
	Progress *bool `protobuf:"varint,3,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	// The tool does not modify its environment. Typical of Get, List and Search.
	ReadOnly *bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3,oneof" json:"read_only,omitempty"`
	// The tool may perform destructive updates. Meaningful only when read_only is
	// false. Typical of Delete, and of Update that replaces rather than merges.
	Destructive *bool `protobuf:"varint,5,opt,name=destructive,proto3,oneof" json:"destructive,omitempty"`
	// Calling the tool repeatedly with the same arguments has no additional
	// effect. Meaningful only when read_only is false. Delete and Update are
	// idempotent under AIP-134; Create generally is not.
	Idempotent *bool `protobuf:"varint,6,opt,name=idempotent,proto3,oneof" json:"idempotent,omitempty"`
	// The tool interacts with an open world of external entities — a third-party
	// API, the public internet — rather than a closed, predictable domain.
	OpenWorld     *bool `protobuf:"varint,7,opt,name=open_world,json=openWorld,proto3,oneof" json:"open_world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPToolOptions) Reset() {
	*x = MCPToolOptions{}
	mi := &file_mcp_v1_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPToolOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPToolOptions) ProtoMessage() {}

func (x *MCPToolOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPToolOptions.ProtoReflect.Descriptor instead.
func (*MCPToolOptions) Descriptor() ([]byte, []int) {
	return file_mcp_v1_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *MCPToolOptions) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *MCPToolOptions) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MCPToolOptions) GetProgress() bool {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return false
}

func (x *MCPToolOptions) GetReadOnly() bool {
	if x != nil && x.ReadOnly != nil {
		return *x.ReadOnly
	}
	return false
}

func (x *MCPToolOptions) GetDestructive() bool {
	if x != nil && x.Destructive != nil {
		return *x.Destructive
	}
	return false
}

func (x *MCPToolOptions) GetIdempotent() bool {
	if x != nil && x.Idempotent != nil {
		return *x.Idempotent
	}
	return false
}

func (x *MCPToolOptions) GetOpenWorld() bool {
	if x != nil && x.OpenWorld != nil {
		return *x.OpenWorld
	}
	return false
}

var File_mcp_v1_prompt_proto protoreflect.FileDescriptor

const file_mcp_v1_prompt_proto_rawDesc = "" +
	"\n" +
	"\x13mcp/v1/prompt.proto\x12\x06mcp.v1\"\x9b\x01\n" +
	"\tMCPPrompt\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\x12#\n" +
	"\x04role\x18\x04 \x01(\x0e2\x0f.mcp.v1.MCPRoleR\x04roleB\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_description\"\xdf\x02\n" +
	"\x0eMCPToolOptions\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x03 \x01(\bH\x02R\bprogress\x88\x01\x01\x12 \n" +
	"\tread_only\x18\x04 \x01(\bH\x03R\breadOnly\x88\x01\x01\x12%\n" +
	"\vdestructive\x18\x05 \x01(\bH\x04R\vdestructive\x88\x01\x01\x12#\n" +
	"\n" +
	"idempotent\x18\x06 \x01(\bH\x05R\n" +
	"idempotent\x88\x01\x01\x12\"\n" +
	"\n" +
	"open_world\x18\a \x01(\bH\x06R\topenWorld\x88\x01\x01B\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_progressB\f\n" +
	"\n" +
	"_read_onlyB\x0e\n" +
	"\f_destructiveB\r\n" +
	"\v_idempotentB\r\n" +
	"\v_open_world*N\n" +
	"\aMCPRole\x12\x18\n" +
	"\x14MCP_ROLE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMCP_ROLE_USER\x10\x01\x12\x16\n" +
	"\x12MCP_ROLE_ASSISTANT\x10\x02BO\n" +
	"\n" +
	"com.mcp.v1B\vPromptProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_prompt_proto_rawDescOnce sync.Once
	file_mcp_v1_prompt_proto_rawDescData []byte
)

func file_mcp_v1_prompt_proto_rawDescGZIP() []byte {
	file_mcp_v1_prompt_proto_rawDescOnce.Do(func() {
		file_mcp_v1_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_prompt_proto_rawDesc), len(file_mcp_v1_prompt_proto_rawDesc)))
	})
	return file_mcp_v1_prompt_proto_rawDescData
}

var file_mcp_v1_prompt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcp_v1_prompt_proto_goTypes = []any{
	(MCPRole)(0),           // 0: mcp.v1.MCPRole
	(*MCPPrompt)(nil),      // 1: mcp.v1.MCPPrompt
	(*MCPToolOptions)(nil), // 2: mcp.v1.MCPToolOptions
}
var file_mcp_v1_prompt_proto_depIdxs = []int32{
	0, // 0: mcp.v1.MCPPrompt.role:type_name -> mcp.v1.MCPRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_v1_prompt_proto_init() }
func file_mcp_v1_prompt_proto_init() {
	if File_mcp_v1_prompt_proto != nil {
		return
	}
	file_mcp_v1_prompt_proto_msgTypes[0].OneofWrappers = []any{}
	file_mcp_v1_prompt_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_prompt_proto_rawDesc), len(file_mcp_v1_prompt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_prompt_proto_goTypes,
		DependencyIndexes: file_mcp_v1_prompt_proto_depIdxs,
		EnumInfos:         file_mcp_v1_prompt_proto_enumTypes,
		MessageInfos:      file_mcp_v1_prompt_proto_msgTypes,
	}.Build()
	File_mcp_v1_prompt_proto = out.File
	file_mcp_v1_prompt_proto_goTypes = nil
	file_mcp_v1_prompt_proto_depIdxs = nil
}
