// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/prompt.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPPrompt defines a reusable prompt template exposed at the service level.
//
// The arguments are defined as a proper proto message referenced by schema.
// Field types, descriptions, required-ness, and enum values are all
// derived from the referenced message's proto definition.
//
// Example:
//
//	prompts: [
//	  {
//	    name: "summarize_todos"
//	    description: "Summarize all pending todo items for a user"
//	    schema: "todo.v1.SummarizeTodosArgs"
//	  }
//	]
type MCPPrompt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique prompt name (e.g. "summarize_todos").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description of what this prompt does.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Fully-qualified proto message name whose fields define the prompt arguments.
	Schema        string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPPrompt) Reset() {
	*x = MCPPrompt{}
	mi := &file_mcp_protobuf_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPPrompt) ProtoMessage() {}

func (x *MCPPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPPrompt.ProtoReflect.Descriptor instead.
func (*MCPPrompt) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *MCPPrompt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPPrompt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPPrompt) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

// MCPToolOptions configures an individual RPC method as an MCP tool.
// Used as: option (mcp.tool) = { ... };
type MCPToolOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override the auto-generated MCP tool name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Override the tool description (defaults to the RPC's leading comment).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// When true, this RPC supports MCP progress notifications. Clients may include
	// progressToken in params._meta; the server will send progress updates during
	// execution. Requires a server-streaming RPC whose response has a oneof with
	// mcp.MCPProgress and the result type.
	Progress      *bool `protobuf:"varint,3,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPToolOptions) Reset() {
	*x = MCPToolOptions{}
	mi := &file_mcp_protobuf_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPToolOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPToolOptions) ProtoMessage() {}

func (x *MCPToolOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPToolOptions.ProtoReflect.Descriptor instead.
func (*MCPToolOptions) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *MCPToolOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPToolOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MCPToolOptions) GetProgress() bool {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return false
}

var File_mcp_protobuf_prompt_proto protoreflect.FileDescriptor

const file_mcp_protobuf_prompt_proto_rawDesc = "" +
	"\n" +
	"\x19mcp/protobuf/prompt.proto\x12\x03mcp\"Y\n" +
	"\tMCPPrompt\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\tR\x06schema\"t\n" +
	"\x0eMCPToolOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\bprogress\x18\x03 \x01(\bH\x00R\bprogress\x88\x01\x01B\v\n" +
	"\t_progressBU\n" +
	"\x10com.mcp.protobufB\vPromptProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_prompt_proto_rawDescOnce sync.Once
	file_mcp_protobuf_prompt_proto_rawDescData []byte
)

func file_mcp_protobuf_prompt_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_prompt_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_prompt_proto_rawDesc), len(file_mcp_protobuf_prompt_proto_rawDesc)))
	})
	return file_mcp_protobuf_prompt_proto_rawDescData
}

var file_mcp_protobuf_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcp_protobuf_prompt_proto_goTypes = []any{
	(*MCPPrompt)(nil),      // 0: mcp.MCPPrompt
	(*MCPToolOptions)(nil), // 1: mcp.MCPToolOptions
}
var file_mcp_protobuf_prompt_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_prompt_proto_init() }
func file_mcp_protobuf_prompt_proto_init() {
	if File_mcp_protobuf_prompt_proto != nil {
		return
	}
	file_mcp_protobuf_prompt_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_prompt_proto_rawDesc), len(file_mcp_protobuf_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_prompt_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_prompt_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_prompt_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_prompt_proto = out.File
	file_mcp_protobuf_prompt_proto_goTypes = nil
	file_mcp_protobuf_prompt_proto_depIdxs = nil
}
