// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/v1/resource.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPIconTheme indicates the background context an icon is designed for.
type MCPIconTheme int32

const (
	// No theme specified. The icon is suitable for any background.
	MCPIconTheme_MCP_ICON_THEME_UNSPECIFIED MCPIconTheme = 0
	// The icon is designed for display on a light background.
	MCPIconTheme_MCP_ICON_THEME_LIGHT MCPIconTheme = 1
	// The icon is designed for display on a dark background.
	MCPIconTheme_MCP_ICON_THEME_DARK MCPIconTheme = 2
)

// Enum value maps for MCPIconTheme.
var (
	MCPIconTheme_name = map[int32]string{
		0: "MCP_ICON_THEME_UNSPECIFIED",
		1: "MCP_ICON_THEME_LIGHT",
		2: "MCP_ICON_THEME_DARK",
	}
	MCPIconTheme_value = map[string]int32{
		"MCP_ICON_THEME_UNSPECIFIED": 0,
		"MCP_ICON_THEME_LIGHT":       1,
		"MCP_ICON_THEME_DARK":        2,
	}
)

func (x MCPIconTheme) Enum() *MCPIconTheme {
	p := new(MCPIconTheme)
	*p = x
	return p
}

func (x MCPIconTheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPIconTheme) Descriptor() protoreflect.EnumDescriptor {
	return file_mcp_v1_resource_proto_enumTypes[0].Descriptor()
}

func (MCPIconTheme) Type() protoreflect.EnumType {
	return &file_mcp_v1_resource_proto_enumTypes[0]
}

func (x MCPIconTheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPIconTheme.Descriptor instead.
func (MCPIconTheme) EnumDescriptor() ([]byte, []int) {
	return file_mcp_v1_resource_proto_rawDescGZIP(), []int{0}
}

// MCPAnnotations carries audience and priority metadata attached to a resource.
// It corresponds to the Annotations struct in the MCP Go SDK.
type MCPAnnotations struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Who the resource is intended for. May contain multiple values to indicate
	// content useful for more than one audience (e.g. both user and assistant).
	Audience []MCPRole `protobuf:"varint,1,rep,packed,name=audience,proto3,enum=mcp.v1.MCPRole" json:"audience,omitempty"`
	// ISO 8601 formatted timestamp of when the resource was last modified.
	// Examples: last activity in an open file, time the resource was attached.
	LastModified *string `protobuf:"bytes,2,opt,name=last_modified,json=lastModified,proto3,oneof" json:"last_modified,omitempty"`
	// Describes how important this data is for operating the server.
	// A value of 1.0 means "most important" (effectively required);
	// 0.0 means "least important" (entirely optional).
	Priority      *float64 `protobuf:"fixed64,3,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPAnnotations) Reset() {
	*x = MCPAnnotations{}
	mi := &file_mcp_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPAnnotations) ProtoMessage() {}

func (x *MCPAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPAnnotations.ProtoReflect.Descriptor instead.
func (*MCPAnnotations) Descriptor() ([]byte, []int) {
	return file_mcp_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *MCPAnnotations) GetAudience() []MCPRole {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *MCPAnnotations) GetLastModified() string {
	if x != nil && x.LastModified != nil {
		return *x.LastModified
	}
	return ""
}

func (x *MCPAnnotations) GetPriority() float64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

// MCPIcon describes a single icon image associated with a resource.
// It corresponds to the Icon struct in the MCP Go SDK.
type MCPIcon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI pointing to the icon resource. This can be an HTTP/HTTPS URL pointing
	// to an image file, or an inline `data:` URI carrying the image bytes.
	// Required.
	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	// MIME type of the icon image. Should be provided when the server's
	// Content-Type header is missing or too generic.
	MimeType *string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3,oneof" json:"mime_type,omitempty"`
	// Size specification for the icon. Examples:
	//
	//	["48x48"]           — single fixed size
	//	["any"]             — scalable format such as SVG
	//	["48x48", "96x96"]  — multiple available sizes
	Sizes []string `protobuf:"bytes,3,rep,name=sizes,proto3" json:"sizes,omitempty"`
	// The background context this icon is designed for.
	// Omit if the icon is suitable for any background.
	Theme         MCPIconTheme `protobuf:"varint,4,opt,name=theme,proto3,enum=mcp.v1.MCPIconTheme" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPIcon) Reset() {
	*x = MCPIcon{}
	mi := &file_mcp_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPIcon) ProtoMessage() {}

func (x *MCPIcon) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPIcon.ProtoReflect.Descriptor instead.
func (*MCPIcon) Descriptor() ([]byte, []int) {
	return file_mcp_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *MCPIcon) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MCPIcon) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *MCPIcon) GetSizes() []string {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *MCPIcon) GetTheme() MCPIconTheme {
	if x != nil {
		return x.Theme
	}
	return MCPIconTheme_MCP_ICON_THEME_UNSPECIFIED
}

// MCPResource describes an MCP resource exposed by a gRPC service.
// It corresponds to the Resource struct in the MCP Go SDK.
//
// Either uri or pattern must be set (enforced by the oneof).
// Use uri for a concrete resource at a fixed location.
// Use pattern for a URI template that matches a family of resources.
type MCPResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies whether this is a concrete resource (uri) or a URI-template
	// resource (pattern). Exactly one must be set.
	//
	// Types that are valid to be assigned to UriOrPattern:
	//
	//	*MCPResource_Uri
	//	*MCPResource_Pattern
	UriOrPattern isMCPResource_UriOrPattern `protobuf_oneof:"uri_or_pattern"`
	// Programmatic identifier for the resource. Used as the display name when
	// title is absent.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable display name, optimised for UI and end-user contexts.
	// Preferred over name when both are present.
	Title *string `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// A description of what this resource represents. Clients may use this
	// as a hint to help the LLM understand what the resource contains.
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// The MIME type of the resource content, if known, e.g. "application/json"
	// or "text/markdown".
	MimeType string `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The size of the raw resource content in bytes (before any base64 encoding
	// or tokenisation), if known. Clients may use this to estimate context usage.
	Size *int64 `protobuf:"varint,7,opt,name=size,proto3,oneof" json:"size,omitempty"`
	// Optional annotations describing intended audience and priority.
	Annotations *MCPAnnotations `protobuf:"bytes,8,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	// Icons representing the resource in client UIs.
	Icons         []*MCPIcon `protobuf:"bytes,9,rep,name=icons,proto3" json:"icons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPResource) Reset() {
	*x = MCPResource{}
	mi := &file_mcp_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPResource) ProtoMessage() {}

func (x *MCPResource) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPResource.ProtoReflect.Descriptor instead.
func (*MCPResource) Descriptor() ([]byte, []int) {
	return file_mcp_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *MCPResource) GetUriOrPattern() isMCPResource_UriOrPattern {
	if x != nil {
		return x.UriOrPattern
	}
	return nil
}

func (x *MCPResource) GetUri() string {
	if x != nil {
		if x, ok := x.UriOrPattern.(*MCPResource_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *MCPResource) GetPattern() string {
	if x != nil {
		if x, ok := x.UriOrPattern.(*MCPResource_Pattern); ok {
			return x.Pattern
		}
	}
	return ""
}

func (x *MCPResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MCPResource) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *MCPResource) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MCPResource) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MCPResource) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *MCPResource) GetAnnotations() *MCPAnnotations {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *MCPResource) GetIcons() []*MCPIcon {
	if x != nil {
		return x.Icons
	}
	return nil
}

type isMCPResource_UriOrPattern interface {
	isMCPResource_UriOrPattern()
}

type MCPResource_Uri struct {
	// The URI of a specific resource, e.g. "file:///home/user/report.pdf".
	Uri string `protobuf:"bytes,1,opt,name=uri,proto3,oneof"`
}

type MCPResource_Pattern struct {
	// A URI template pattern for a family of resources,
	// e.g. "file:///home/user/{filename}".
	Pattern string `protobuf:"bytes,2,opt,name=pattern,proto3,oneof"`
}

func (*MCPResource_Uri) isMCPResource_UriOrPattern() {}

func (*MCPResource_Pattern) isMCPResource_UriOrPattern() {}

var File_mcp_v1_resource_proto protoreflect.FileDescriptor

const file_mcp_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x15mcp/v1/resource.proto\x12\x06mcp.v1\x1a\x13mcp/v1/prompt.proto\"\xa7\x01\n" +
	"\x0eMCPAnnotations\x12+\n" +
	"\baudience\x18\x01 \x03(\x0e2\x0f.mcp.v1.MCPRoleR\baudience\x12(\n" +
	"\rlast_modified\x18\x02 \x01(\tH\x00R\flastModified\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x03 \x01(\x01H\x01R\bpriority\x88\x01\x01B\x10\n" +
	"\x0e_last_modifiedB\v\n" +
	"\t_priority\"\x8d\x01\n" +
	"\aMCPIcon\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12 \n" +
	"\tmime_type\x18\x02 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x14\n" +
	"\x05sizes\x18\x03 \x03(\tR\x05sizes\x12*\n" +
	"\x05theme\x18\x04 \x01(\x0e2\x14.mcp.v1.MCPIconThemeR\x05themeB\f\n" +
	"\n" +
	"_mime_type\"\xf0\x02\n" +
	"\vMCPResource\x12\x12\n" +
	"\x03uri\x18\x01 \x01(\tH\x00R\x03uri\x12\x1a\n" +
	"\apattern\x18\x02 \x01(\tH\x00R\apattern\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x01R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x17\n" +
	"\x04size\x18\a \x01(\x03H\x03R\x04size\x88\x01\x01\x12=\n" +
	"\vannotations\x18\b \x01(\v2\x16.mcp.v1.MCPAnnotationsH\x04R\vannotations\x88\x01\x01\x12%\n" +
	"\x05icons\x18\t \x03(\v2\x0f.mcp.v1.MCPIconR\x05iconsB\x10\n" +
	"\x0euri_or_patternB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_sizeB\x0e\n" +
	"\f_annotations*a\n" +
	"\fMCPIconTheme\x12\x1e\n" +
	"\x1aMCP_ICON_THEME_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MCP_ICON_THEME_LIGHT\x10\x01\x12\x17\n" +
	"\x13MCP_ICON_THEME_DARK\x10\x02BQ\n" +
	"\n" +
	"com.mcp.v1B\rResourceProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_v1_resource_proto_rawDescOnce sync.Once
	file_mcp_v1_resource_proto_rawDescData []byte
)

func file_mcp_v1_resource_proto_rawDescGZIP() []byte {
	file_mcp_v1_resource_proto_rawDescOnce.Do(func() {
		file_mcp_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_resource_proto_rawDesc), len(file_mcp_v1_resource_proto_rawDesc)))
	})
	return file_mcp_v1_resource_proto_rawDescData
}

var file_mcp_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcp_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mcp_v1_resource_proto_goTypes = []any{
	(MCPIconTheme)(0),      // 0: mcp.v1.MCPIconTheme
	(*MCPAnnotations)(nil), // 1: mcp.v1.MCPAnnotations
	(*MCPIcon)(nil),        // 2: mcp.v1.MCPIcon
	(*MCPResource)(nil),    // 3: mcp.v1.MCPResource
	(MCPRole)(0),           // 4: mcp.v1.MCPRole
}
var file_mcp_v1_resource_proto_depIdxs = []int32{
	4, // 0: mcp.v1.MCPAnnotations.audience:type_name -> mcp.v1.MCPRole
	0, // 1: mcp.v1.MCPIcon.theme:type_name -> mcp.v1.MCPIconTheme
	1, // 2: mcp.v1.MCPResource.annotations:type_name -> mcp.v1.MCPAnnotations
	2, // 3: mcp.v1.MCPResource.icons:type_name -> mcp.v1.MCPIcon
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mcp_v1_resource_proto_init() }
func file_mcp_v1_resource_proto_init() {
	if File_mcp_v1_resource_proto != nil {
		return
	}
	file_mcp_v1_prompt_proto_init()
	file_mcp_v1_resource_proto_msgTypes[0].OneofWrappers = []any{}
	file_mcp_v1_resource_proto_msgTypes[1].OneofWrappers = []any{}
	file_mcp_v1_resource_proto_msgTypes[2].OneofWrappers = []any{
		(*MCPResource_Uri)(nil),
		(*MCPResource_Pattern)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_resource_proto_rawDesc), len(file_mcp_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_v1_resource_proto_goTypes,
		DependencyIndexes: file_mcp_v1_resource_proto_depIdxs,
		EnumInfos:         file_mcp_v1_resource_proto_enumTypes,
		MessageInfos:      file_mcp_v1_resource_proto_msgTypes,
	}.Build()
	File_mcp_v1_resource_proto = out.File
	file_mcp_v1_resource_proto_goTypes = nil
	file_mcp_v1_resource_proto_depIdxs = nil
}
