// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp/protobuf/service_options.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPServiceOptions configures MCP behaviour for an entire gRPC service.
type MCPServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// App-level metadata surfaced to MCP clients.
	App           *MCPApp `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServiceOptions) Reset() {
	*x = MCPServiceOptions{}
	mi := &file_mcp_protobuf_service_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServiceOptions) ProtoMessage() {}

func (x *MCPServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_protobuf_service_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServiceOptions.ProtoReflect.Descriptor instead.
func (*MCPServiceOptions) Descriptor() ([]byte, []int) {
	return file_mcp_protobuf_service_options_proto_rawDescGZIP(), []int{0}
}

func (x *MCPServiceOptions) GetApp() *MCPApp {
	if x != nil {
		return x.App
	}
	return nil
}

var File_mcp_protobuf_service_options_proto protoreflect.FileDescriptor

const file_mcp_protobuf_service_options_proto_rawDesc = "" +
	"\n" +
	"\"mcp/protobuf/service_options.proto\x12\x03mcp\x1a\x16mcp/protobuf/app.proto\"2\n" +
	"\x11MCPServiceOptions\x12\x1d\n" +
	"\x03app\x18\x01 \x01(\v2\v.mcp.MCPAppR\x03appB]\n" +
	"\x10com.mcp.protobufB\x13ServiceOptionsProtoP\x01Z2github.com/the-protobuf-project/mcp/protobuf/mcppbb\x06proto3"

var (
	file_mcp_protobuf_service_options_proto_rawDescOnce sync.Once
	file_mcp_protobuf_service_options_proto_rawDescData []byte
)

func file_mcp_protobuf_service_options_proto_rawDescGZIP() []byte {
	file_mcp_protobuf_service_options_proto_rawDescOnce.Do(func() {
		file_mcp_protobuf_service_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_protobuf_service_options_proto_rawDesc), len(file_mcp_protobuf_service_options_proto_rawDesc)))
	})
	return file_mcp_protobuf_service_options_proto_rawDescData
}

var file_mcp_protobuf_service_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_protobuf_service_options_proto_goTypes = []any{
	(*MCPServiceOptions)(nil), // 0: mcp.MCPServiceOptions
	(*MCPApp)(nil),            // 1: mcp.MCPApp
}
var file_mcp_protobuf_service_options_proto_depIdxs = []int32{
	1, // 0: mcp.MCPServiceOptions.app:type_name -> mcp.MCPApp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_protobuf_service_options_proto_init() }
func file_mcp_protobuf_service_options_proto_init() {
	if File_mcp_protobuf_service_options_proto != nil {
		return
	}
	file_mcp_protobuf_app_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_protobuf_service_options_proto_rawDesc), len(file_mcp_protobuf_service_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_protobuf_service_options_proto_goTypes,
		DependencyIndexes: file_mcp_protobuf_service_options_proto_depIdxs,
		MessageInfos:      file_mcp_protobuf_service_options_proto_msgTypes,
	}.Build()
	File_mcp_protobuf_service_options_proto = out.File
	file_mcp_protobuf_service_options_proto_goTypes = nil
	file_mcp_protobuf_service_options_proto_depIdxs = nil
}
